/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import DBconnetions.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class add_sessions extends javax.swing.JPanel {
    
    Generator generator;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form sessions
     */
    public add_sessions() {
        initComponents();
        con = DBconnect.connect();
        lecSession1();
        subNameSession();
        subCodeSession();
        tagSession();
        group1();
        group2();
        sub2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel111_addSession = new javax.swing.JPanel();
        jLabel2_addSession = new javax.swing.JLabel();
        jLabel3_addSession = new javax.swing.JLabel();
        jLabel4_addSession = new javax.swing.JLabel();
        jLabel5_addSession = new javax.swing.JLabel();
        jLabel6_addSession = new javax.swing.JLabel();
        jLabel7_addSession = new javax.swing.JLabel();
        jLabel8_addSession = new javax.swing.JLabel();
        jLabel9_addSession = new javax.swing.JLabel();
        jLabel10_addSession = new javax.swing.JLabel();
        tag_addSession = new javax.swing.JComboBox<>();
        group1_addSession = new javax.swing.JComboBox<>();
        group2_addSession = new javax.swing.JComboBox<>();
        group_addSession = new javax.swing.JTextField();
        sub2_addSession = new javax.swing.JComboBox<>();
        subName__addSession = new javax.swing.JComboBox<>();
        subCode_addSession = new javax.swing.JComboBox<>();
        students_addSession = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        session_addSession = new javax.swing.JTextArea();
        addGroup_addSession = new javax.swing.JButton();
        generate_addSession = new javax.swing.JButton();
        lecurersselect_addSession = new javax.swing.JComboBox<>();
        select_addSession = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturers_addSession = new javax.swing.JTextArea();
        id_addSession = new javax.swing.JTextField();
        jLabel11_addSession = new javax.swing.JLabel();
        duration_addSession1 = new javax.swing.JTextField();
        create_addSession = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 51, 109));

        panel111_addSession.setBackground(new java.awt.Color(137, 14, 137));
        panel111_addSession.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Session Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel111_addSession.setToolTipText("Select");

        jLabel2_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_addSession.setText("Lecturer(s)");

        jLabel3_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_addSession.setText("Session ID");

        jLabel4_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_addSession.setText("Group");

        jLabel5_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_addSession.setText("Tag");

        jLabel6_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_addSession.setText("Sub-group");

        jLabel7_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7_addSession.setText("Subject Name");

        jLabel8_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8_addSession.setText("Subject Code");

        jLabel9_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9_addSession.setText("Student Count");

        jLabel10_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10_addSession.setText("Session");

        tag_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tag_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Tag" }));
        tag_addSession.setBorder(null);
        tag_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_addSessionActionPerformed(evt);
            }
        });

        group1_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group1_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batch" }));
        group1_addSession.setBorder(null);

        group2_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group2_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Group" }));
        group2_addSession.setBorder(null);

        group_addSession.setEditable(false);
        group_addSession.setBackground(new java.awt.Color(255, 255, 255));
        group_addSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_addSessionActionPerformed(evt);
            }
        });

        sub2_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sub2_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub-group" }));
        sub2_addSession.setBorder(null);

        subName__addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subName__addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Name" }));
        subName__addSession.setBorder(null);

        subCode_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subCode_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Code" }));
        subCode_addSession.setBorder(null);

        students_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students_addSession.setBorder(null);
        students_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_addSessionActionPerformed(evt);
            }
        });
        students_addSession.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                students_addSessionKeyPressed(evt);
            }
        });

        session_addSession.setEditable(false);
        session_addSession.setColumns(20);
        session_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        session_addSession.setRows(5);
        session_addSession.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(session_addSession);

        addGroup_addSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addGroup_addSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        addGroup_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroup_addSessionActionPerformed(evt);
            }
        });

        generate_addSession.setBackground(new java.awt.Color(102, 0, 102));
        generate_addSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generate_addSession.setText("Generate Session");
        generate_addSession.setBorder(null);
        generate_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_addSessionActionPerformed(evt);
            }
        });

        lecurersselect_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecurersselect_addSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lecturer" }));
        lecurersselect_addSession.setBorder(null);
        lecurersselect_addSession.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        select_addSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select_addSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        select_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_addSessionActionPerformed(evt);
            }
        });

        lecturers_addSession.setColumns(20);
        lecturers_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecturers_addSession.setRows(5);
        lecturers_addSession.setBorder(null);
        jScrollPane1.setViewportView(lecturers_addSession);

        id_addSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_addSession.setBorder(null);
        id_addSession.setMinimumSize(new java.awt.Dimension(0, 20));
        id_addSession.setPreferredSize(new java.awt.Dimension(0, 20));
        id_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_addSessionActionPerformed(evt);
            }
        });

        jLabel11_addSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11_addSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11_addSession.setText("Duration");

        duration_addSession1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration_addSession1.setBorder(null);
        duration_addSession1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration_addSession1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel111_addSessionLayout = new javax.swing.GroupLayout(panel111_addSession);
        panel111_addSession.setLayout(panel111_addSessionLayout);
        panel111_addSessionLayout.setHorizontalGroup(
            panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8_addSession)
                                            .addComponent(jLabel7_addSession))
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel5_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel4_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel9_addSession)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_addSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11_addSession)
                                            .addComponent(jLabel10_addSession))
                                        .addGap(46, 46, 46)))))
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lecurersselect_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tag_addSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subCode_addSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subName__addSession, javax.swing.GroupLayout.Alignment.LEADING, 0, 358, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(select_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(students_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duration_addSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addComponent(group1_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(group2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addGroup_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(group_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(generate_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel111_addSessionLayout.setVerticalGroup(
            panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_addSession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3_addSession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lecurersselect_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subName__addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subCode_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addComponent(tag_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(group2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(group1_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addGroup_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel111_addSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(group_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addComponent(jLabel5_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub2_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(students_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_addSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generate_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panel111_addSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel111_addSessionLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel10_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(870, 870, 870))
        );

        create_addSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        create_addSession.setText("Create New Session");
        create_addSession.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        create_addSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_addSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(538, 538, 538)
                        .addComponent(create_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(panel111_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel111_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(create_addSession, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void id_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_addSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_addSessionActionPerformed

    private void group_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_addSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_group_addSessionActionPerformed

    private void students_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_addSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_students_addSessionActionPerformed

    private void create_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_addSessionActionPerformed
        // TODO add your handling code here:
        
        String sessionId = id_addSession.getText();
        String lecturer = lecturers_addSession.getText();
        String subName = subName__addSession.getSelectedItem().toString();
        String subCode = subCode_addSession.getSelectedItem().toString();
        String tag = tag_addSession.getSelectedItem().toString();
        String group = group_addSession.getText();
        String subgroup = sub2_addSession.getSelectedItem().toString();
        int count = Integer.parseInt(students_addSession.getText());
        String sessions = session_addSession.getText();
        String duration = duration_addSession1.getText();
        

        try {

            //Check if there are any empty field before adding details to the database
            if (duration_addSession1.getText().isEmpty() || lecturers_addSession.getText().isEmpty() || subName__addSession.getSelectedItem().equals("Select Subject Name") || subCode_addSession.getSelectedItem().equals("Select Subject Code") || tag_addSession.getSelectedItem().equals("Select Tag") || group_addSession.getText().isEmpty() || students_addSession.getText().isEmpty() || session_addSession.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Invalid Input");

            }

            else {

                //add a new session to the database
                Statement s = con.createStatement();
                String id = tag_addSession.getSelectedItem().toString();
                             
                if (id.equals("practical")){
                    
                    s.execute("INSERT INTO sessions(sessionID,lecturer,tag,groupNo,subgroupNo,subName,subCode,students,duration,sessions) values('" + sessionId + "','" + lecturer + "','" + tag + "','" + group + "'," + subgroup + ",'" + subName + "','" + subCode + "'," + count + ",'" + duration +"','"+ sessions +"')");

                        JOptionPane.showMessageDialog(this, "Records Are Submitted!");
                    
                }
                
                else {
                    
                     s.execute("INSERT INTO sessions(sessionID,lecturer,tag,groupNo,subName,subCode,students,duration,sessions) values('" + sessionId + "','" + lecturer + "','" + tag + "','" + group + "','" + subName + "','" + subCode + "'," + count + ",'" + duration +"','"+ sessions +"')");

                        JOptionPane.showMessageDialog(this, "Records Are Submitted!");
                
                }

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex);

        }    
        
    }//GEN-LAST:event_create_addSessionActionPerformed

    private void addGroup_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroup_addSessionActionPerformed
        // TODO add your handling code here:
        
        String group1 = group1_addSession.getSelectedItem().toString();
        String group2 = group2_addSession.getSelectedItem().toString();

        String group = group1 + "." + group2;

        //concatenate and display the batch and group no
        group_addSession.setText(group);
                              
    }//GEN-LAST:event_addGroup_addSessionActionPerformed

    private void generate_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_addSessionActionPerformed
        // TODO add your handling code here:
        String lecturer = lecturers_addSession.getText();
        String subName = subName__addSession.getSelectedItem().toString();
        String subCode = subCode_addSession.getSelectedItem().toString();
        String tag = tag_addSession.getSelectedItem().toString();
        String group = group_addSession.getText().toString();
        String subgroup = sub2_addSession.getSelectedItem().toString();
        int count = Integer.parseInt(students_addSession.getText());
        String duration = duration_addSession1.getText().toString();
        
        //display the generated session
        
        String id = tag_addSession.getSelectedItem().toString();
        
        if (id.equals("practical")){
        
            String session = lecturer  + "\n" + subName + "" + "("  + subCode + ")"  + "\n" + tag + "\n" + group + "\n" + subgroup  + "\n" + count + "(" + duration + ")";
        
            session_addSession.setText(session);
        
        }
        else{
            
            String session = lecturer  + "\n" + subName + "" + "("  + subCode + ")" + "\n" + tag + "\n" + group + "\n" +  count + "(" + duration + ")";
            
            session_addSession.setText(session);
            
        }
               
        
               
    }//GEN-LAST:event_generate_addSessionActionPerformed

    private void select_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_addSessionActionPerformed
        // TODO add your handling code here:

        //add one or more lecturer names
        lecturers_addSession.setText(lecturers_addSession.getText()+lecurersselect_addSession.getSelectedItem().toString()+",");       
        
    }//GEN-LAST:event_select_addSessionActionPerformed

    private void tag_addSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_addSessionActionPerformed
        // TODO add your handling code here:
        String id = tag_addSession.getSelectedItem().toString();

            if (id.equals("practical")) {

               sub2_addSession.setEnabled(true);

            } 
            else {

               sub2_addSession.setEnabled(false);

            }
    }//GEN-LAST:event_tag_addSessionActionPerformed

    private void duration_addSession1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration_addSession1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duration_addSession1ActionPerformed

    private void students_addSessionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_students_addSessionKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        String id = students_addSession.getText();

        //check if this textField contain only numbers and backspace is allowed
        if (Character.isDigit(c) || Character.isISOControl(c)) {   

               students_addSession.setEditable(true);

        } else {

            students_addSession.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Numbers!");

        }
        
    }//GEN-LAST:event_students_addSessionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup_addSession;
    private javax.swing.JButton create_addSession;
    private javax.swing.JTextField duration_addSession1;
    private javax.swing.JButton generate_addSession;
    private javax.swing.JComboBox<String> group1_addSession;
    private javax.swing.JComboBox<String> group2_addSession;
    private javax.swing.JTextField group_addSession;
    private javax.swing.JTextField id_addSession;
    private javax.swing.JLabel jLabel10_addSession;
    private javax.swing.JLabel jLabel11_addSession;
    private javax.swing.JLabel jLabel2_addSession;
    private javax.swing.JLabel jLabel3_addSession;
    private javax.swing.JLabel jLabel4_addSession;
    private javax.swing.JLabel jLabel5_addSession;
    private javax.swing.JLabel jLabel6_addSession;
    private javax.swing.JLabel jLabel7_addSession;
    private javax.swing.JLabel jLabel8_addSession;
    private javax.swing.JLabel jLabel9_addSession;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lecturers_addSession;
    private javax.swing.JComboBox<String> lecurersselect_addSession;
    private javax.swing.JPanel panel111_addSession;
    private javax.swing.JButton select_addSession;
    private javax.swing.JTextArea session_addSession;
    private javax.swing.JTextField students_addSession;
    private javax.swing.JComboBox<String> sub2_addSession;
    private javax.swing.JComboBox<String> subCode_addSession;
    private javax.swing.JComboBox<String> subName__addSession;
    private javax.swing.JComboBox<String> tag_addSession;
    // End of variables declaration//GEN-END:variables
  
    
    //load the combo boxes
    
private void lecSession1(){      
        String sql = "select * from lec";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                lecurersselect_addSession.addItem(rs.getString("name"));                
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void subNameSession(){      
        String sql = "select * from subject";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                subName__addSession.addItem(rs.getString("name"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void subCodeSession(){      
        String sql = "select * from subject";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                subCode_addSession.addItem(rs.getString("code"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void tagSession(){      
        
    String sql = "select * from tag";  
        
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                tag_addSession.addItem(rs.getString("tag"));   
            }         }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void group1(){      
        String sql = "select * from groups";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                group1_addSession.addItem(rs.getString("batch"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void group2(){      
        String sql = "select * from groups";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                group2_addSession.addItem(rs.getString("groups"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void sub2(){      
        String sql = "select * from subgroup";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                sub2_addSession.addItem(rs.getString("sub_group"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

}
