/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import DBconnetions.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Shakith
 */
public class lecturer_add extends javax.swing.JPanel {

    Generator generator;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    view_lecturers view;
    /**
     * Creates new form lecturer_add
     */
    public lecturer_add() {
        initComponents();
        con = DBconnect.connect();
        buildinglecturer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturer_add = new javax.swing.JPanel();
        lecturer_add1 = new javax.swing.JPanel();
        adds_lec = new javax.swing.JButton();
        jButton2_2 = new javax.swing.JButton();
        jButton13_addlecdetails = new javax.swing.JButton();
        jPanel33_addlecdetails = new javax.swing.JPanel();
        jLabel38_addlecdetails = new javax.swing.JLabel();
        la = new javax.swing.JTextField();
        jLabel23_addlecdetails = new javax.swing.JLabel();
        la1 = new javax.swing.JTextField();
        jLabel39_addlecdetails = new javax.swing.JLabel();
        jLabel40_addlecdetails = new javax.swing.JLabel();
        jLabel41_addlecdetails = new javax.swing.JLabel();
        jLabel42_addlecdetails = new javax.swing.JLabel();
        jLabel43_addlecdetails = new javax.swing.JLabel();
        la2 = new javax.swing.JComboBox<>();
        la3 = new javax.swing.JComboBox<>();
        la4 = new javax.swing.JComboBox<>();
        la5 = new javax.swing.JComboBox<>();
        la6 = new javax.swing.JComboBox<>();
        jLabel44_addlecdetails = new javax.swing.JLabel();
        la7 = new javax.swing.JTextField();
        jLabel45_addlecdetails = new javax.swing.JLabel();
        jButton8_addlecdetails = new javax.swing.JButton();
        jScrollPane1_1 = new javax.swing.JScrollPane();
        jTable1_addlecdetails = new javax.swing.JTable();

        lecturer_add1.setBackground(new java.awt.Color(102, 51, 109));

        adds_lec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adds_lec.setText(" Add Lecturer ");
        adds_lec.setBorder(null);
        adds_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adds_lecActionPerformed(evt);
            }
        });
        adds_lec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adds_lecKeyPressed(evt);
            }
        });

        jButton2_2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2_2.setText(" Generate ");
        jButton2_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton13_addlecdetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13_addlecdetails.setText(" Back ");
        jButton13_addlecdetails.setBorder(null);
        jButton13_addlecdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13_addlecdetailsActionPerformed(evt);
            }
        });

        jPanel33_addlecdetails.setBackground(new java.awt.Color(137, 14, 137));
        jPanel33_addlecdetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Lecturer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel38_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel38_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38_addlecdetails.setText("Employee ID");

        la.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la.setBorder(null);
        la.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laActionPerformed(evt);
            }
        });
        la.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                laKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                laKeyTyped(evt);
            }
        });

        jLabel23_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel23_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23_addlecdetails.setText("Name");

        la1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la1.setBorder(null);
        la1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la1ActionPerformed(evt);
            }
        });
        la1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                la1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                la1KeyReleased(evt);
            }
        });

        jLabel39_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel39_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39_addlecdetails.setText("Faculty");

        jLabel40_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel40_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40_addlecdetails.setText("Department");

        jLabel41_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel41_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41_addlecdetails.setText("Center");

        jLabel42_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel42_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42_addlecdetails.setText("Building");

        jLabel43_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel43_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43_addlecdetails.setText("Level");

        la2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Home Science" }));
        la2.setBorder(null);

        la3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Software Engineering", "Infortmation Technology", "Computer Networks", "Interactive Media", "Civil Engineering", "Mechanical Engineering", "Electronic and Telecommuincation Engineering", "Humanities and Science", "Cyber Securrity", "Information System Engineering", "Mechatronic Engineering" }));
        la3.setBorder(null);

        la4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Center", "Malabe", "Matara", "Kandy", "Jaffna", "Metro", "Kurunegala" }));
        la4.setBorder(null);

        la5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building" }));
        la5.setBorder(null);

        la6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));
        la6.setBorder(null);

        jLabel44_addlecdetails.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel44_addlecdetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44_addlecdetails.setText("Rank");

        la7.setEditable(false);
        la7.setBackground(new java.awt.Color(255, 255, 255));
        la7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        la7.setBorder(null);
        la7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la7ActionPerformed(evt);
            }
        });
        la7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                la7KeyPressed(evt);
            }
        });

        jLabel45_addlecdetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45_addlecdetails.setForeground(new java.awt.Color(255, 0, 51));
        jLabel45_addlecdetails.setText("*Level.EmployeeID");

        jButton8_addlecdetails.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8_addlecdetails.setText(" Generate ");
        jButton8_addlecdetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8_addlecdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8_addlecdetailsActionPerformed(evt);
            }
        });

        jTable1_addlecdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Professor", "1"},
                {"Assistant Professor", "2"},
                {"Senior Lecturer (HG)", "3"},
                {"Senior Lecturer ", "4"},
                {"Lecturer", "5"},
                {"Assistant Lecturer", "6"},
                {"Instructor", "7"}
            },
            new String [] {
                "Category", "Level"
            }
        ));
        jScrollPane1_1.setViewportView(jTable1_addlecdetails);

        javax.swing.GroupLayout jPanel33_addlecdetailsLayout = new javax.swing.GroupLayout(jPanel33_addlecdetails);
        jPanel33_addlecdetails.setLayout(jPanel33_addlecdetailsLayout);
        jPanel33_addlecdetailsLayout.setHorizontalGroup(
            jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33_addlecdetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_addlecdetailsLayout.createSequentialGroup()
                        .addComponent(la7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton8_addlecdetails)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_addlecdetailsLayout.createSequentialGroup()
                        .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel40_addlecdetails)
                                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42_addlecdetails)
                                    .addComponent(jLabel41_addlecdetails, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel44_addlecdetails)
                                        .addComponent(jLabel43_addlecdetails)))
                                .addComponent(jLabel39_addlecdetails)
                                .addComponent(jLabel23_addlecdetails))
                            .addComponent(jLabel38_addlecdetails, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(la1)
                            .addComponent(la2, 0, 249, Short.MAX_VALUE)
                            .addComponent(la3, 0, 1, Short.MAX_VALUE)
                            .addComponent(la)
                            .addComponent(la4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(la5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(la6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_addlecdetailsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_addlecdetailsLayout.createSequentialGroup()
                        .addComponent(jLabel45_addlecdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(158, 158, 158))))
        );
        jPanel33_addlecdetailsLayout.setVerticalGroup(
            jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33_addlecdetailsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38_addlecdetails)
                    .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23_addlecdetails)
                    .addComponent(la1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39_addlecdetails)
                    .addComponent(la2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40_addlecdetails)
                    .addComponent(la3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41_addlecdetails))
                .addGap(35, 35, 35)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(la5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42_addlecdetails))
                .addGap(28, 28, 28)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43_addlecdetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel33_addlecdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44_addlecdetails)
                    .addComponent(jButton8_addlecdetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel45_addlecdetails)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout lecturer_add1Layout = new javax.swing.GroupLayout(lecturer_add1);
        lecturer_add1.setLayout(lecturer_add1Layout);
        lecturer_add1Layout.setHorizontalGroup(
            lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturer_add1Layout.createSequentialGroup()
                .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lecturer_add1Layout.createSequentialGroup()
                        .addGap(611, 611, 611)
                        .addComponent(jButton13_addlecdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(adds_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lecturer_add1Layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jPanel33_addlecdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3652, Short.MAX_VALUE))
            .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_add1Layout.createSequentialGroup()
                    .addGap(1481, 1481, 1481)
                    .addComponent(jButton2_2)
                    .addContainerGap(3106, Short.MAX_VALUE)))
        );
        lecturer_add1Layout.setVerticalGroup(
            lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lecturer_add1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel33_addlecdetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adds_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13_addlecdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1159, Short.MAX_VALUE))
            .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_add1Layout.createSequentialGroup()
                    .addContainerGap(1695, Short.MAX_VALUE)
                    .addComponent(jButton2_2)
                    .addGap(266, 266, 266)))
        );

        javax.swing.GroupLayout lecturer_addLayout = new javax.swing.GroupLayout(lecturer_add);
        lecturer_add.setLayout(lecturer_addLayout);
        lecturer_addLayout.setHorizontalGroup(
            lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lecturer_addLayout.createSequentialGroup()
                .addComponent(lecturer_add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        lecturer_addLayout.setVerticalGroup(
            lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturer_addLayout.createSequentialGroup()
                .addComponent(lecturer_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4678, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adds_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adds_lecActionPerformed
        // TODO add your handling code here:

        int empId = Integer.parseInt(la.getText());
        String lecName = la1.getText();
        String lecFaculty = la2.getSelectedItem().toString();
        String lecDepartment = la3.getSelectedItem().toString();
        String lecCenter = la4.getSelectedItem().toString();
        String lecBulding = la5.getSelectedItem().toString();
        int lecLevel = Integer.parseInt(la6.getSelectedItem().toString());
        String lecRank = la7.getText();

        String id = la.getText();

        int length = id.length();
        
        
        //check if the employee ID contain six digits
        if (length < 6) {

                la.setEditable(true);
                JOptionPane.showMessageDialog(this, "Employee ID Should Contain Six Digits");}

        try {

            //Check if there are any empty field before adding details to the database
            if (la.getText().isEmpty() || la1.getText().isEmpty() || la2.getSelectedItem().equals("Select Faculty") || la3.getSelectedItem().equals("Select Department") || la4.getSelectedItem().equals("Select Center") || la5.getSelectedItem().equals("Select Building") || la6.getSelectedItem().equals("Select Level") || la7.getText().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Invalid Input");

            } else {
                    
                //add a new lecturer to the database
                Statement s = con.createStatement();
                s.execute("INSERT INTO lec(empID,name,faculty,dept,center,building,level,rank) values(" + empId + ",'" + lecName + "','" + lecFaculty + "','" + lecDepartment + "','" + lecCenter + "','" + lecBulding + "'," + lecLevel + ",'" + lecRank + "')");

                JOptionPane.showMessageDialog(this, "Records Are Submitted!");

                resetEmpData();
                    
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_adds_lecActionPerformed

    private void adds_lecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adds_lecKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adds_lecKeyPressed

    private void jButton13_addlecdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13_addlecdetailsActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturersPanel());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jButton13_addlecdetailsActionPerformed

    private void laActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laActionPerformed

    private void laKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        String id = la.getText();

        int length = id.length();

        //check if this textField contain only numbers and backspace is allowed
        if (Character.isDigit(c) || Character.isISOControl(c)) {

            //check if the employee id contains six digits
            if (length < 6) {

                la.setEditable(true);

            } else {

                la.setEditable(false);

            }

        } else {

            la.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Numbers!");

        }
    }//GEN-LAST:event_laKeyPressed

    private void laKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_laKeyTyped

    private void la1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_la1ActionPerformed

    private void la1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_la1KeyPressed

    private void la1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_la1KeyReleased

    private void la7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_la7ActionPerformed

    private void la7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_la7KeyPressed

    private void jButton8_addlecdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_addlecdetailsActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(la.getText());
        int level = Integer.parseInt(la6.getSelectedItem().toString());

        //concatenate the  values of level and id textfields
        String rank = level + "." + id;

        //show the generate rank
        la7.setText("" + rank);
        
    }//GEN-LAST:event_jButton8_addlecdetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adds_lec;
    private javax.swing.JButton jButton13_addlecdetails;
    private javax.swing.JButton jButton2_2;
    private javax.swing.JButton jButton8_addlecdetails;
    private javax.swing.JLabel jLabel23_addlecdetails;
    private javax.swing.JLabel jLabel38_addlecdetails;
    private javax.swing.JLabel jLabel39_addlecdetails;
    private javax.swing.JLabel jLabel40_addlecdetails;
    private javax.swing.JLabel jLabel41_addlecdetails;
    private javax.swing.JLabel jLabel42_addlecdetails;
    private javax.swing.JLabel jLabel43_addlecdetails;
    private javax.swing.JLabel jLabel44_addlecdetails;
    private javax.swing.JLabel jLabel45_addlecdetails;
    private javax.swing.JPanel jPanel33_addlecdetails;
    private javax.swing.JScrollPane jScrollPane1_1;
    private javax.swing.JTable jTable1_addlecdetails;
    public javax.swing.JTextField la;
    public javax.swing.JTextField la1;
    public javax.swing.JComboBox<String> la2;
    public javax.swing.JComboBox<String> la3;
    public javax.swing.JComboBox<String> la4;
    public javax.swing.JComboBox<String> la5;
    public javax.swing.JComboBox<String> la6;
    public javax.swing.JTextField la7;
    private javax.swing.JPanel lecturer_add;
    private javax.swing.JPanel lecturer_add1;
    // End of variables declaration//GEN-END:variables

private void resetEmpData() {

        la.setText("");la1.setText("");la2.setSelectedItem("Select Faculty");la3.setSelectedItem("Select Department");la4.setSelectedItem("Select Center");la5.setSelectedItem("Select Building");la6.setSelectedItem("Select Level");la7.setText("");

    }

private void buildinglecturer(){      
        String sql = "select * from building";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                la5.addItem(rs.getString("Name"));                
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }





}
