/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Shakith
 */
public class lecturer_add extends javax.swing.JPanel {

    Generator generator;
    
    Connection con = null;
    /**
     * Creates new form lecturer_add
     */
    public lecturer_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturer_add = new javax.swing.JPanel();
        lecturer_add1 = new javax.swing.JPanel();
        adds_lec = new javax.swing.JButton();
        jButton2_2 = new javax.swing.JButton();
        jPanel17_17 = new javax.swing.JPanel();
        jLabel46_46 = new javax.swing.JLabel();
        jButton13_13 = new javax.swing.JButton();
        jPanel33_33 = new javax.swing.JPanel();
        jLabel38_38 = new javax.swing.JLabel();
        la = new javax.swing.JTextField();
        jLabel23_23 = new javax.swing.JLabel();
        la1 = new javax.swing.JTextField();
        jLabel39_39 = new javax.swing.JLabel();
        jLabel40_40 = new javax.swing.JLabel();
        jLabel41_41 = new javax.swing.JLabel();
        jLabel42_42 = new javax.swing.JLabel();
        jLabel43_43 = new javax.swing.JLabel();
        la2 = new javax.swing.JComboBox<>();
        la3 = new javax.swing.JComboBox<>();
        la4 = new javax.swing.JComboBox<>();
        la5 = new javax.swing.JComboBox<>();
        la6 = new javax.swing.JComboBox<>();
        jLabel44_44 = new javax.swing.JLabel();
        la7 = new javax.swing.JTextField();
        jLabel45_45 = new javax.swing.JLabel();
        jButton8_8 = new javax.swing.JButton();
        jScrollPane1_1 = new javax.swing.JScrollPane();
        jTable1_1 = new javax.swing.JTable();

        lecturer_add1.setBackground(new java.awt.Color(0, 0, 102));

        adds_lec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adds_lec.setText(" Add Lecturer ");
        adds_lec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        adds_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adds_lecActionPerformed(evt);
            }
        });
        adds_lec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                adds_lecKeyPressed(evt);
            }
        });

        jButton2_2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton2_2.setText(" Generate ");
        jButton2_2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel17_17.setBackground(new java.awt.Color(0, 0, 0));
        jPanel17_17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel46_46.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel46_46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46_46.setText("ADD LECTURER DETAILS");

        javax.swing.GroupLayout jPanel17_17Layout = new javax.swing.GroupLayout(jPanel17_17);
        jPanel17_17.setLayout(jPanel17_17Layout);
        jPanel17_17Layout.setHorizontalGroup(
            jPanel17_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17_17Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel46_46)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel17_17Layout.setVerticalGroup(
            jPanel17_17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17_17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46_46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton13_13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton13_13.setText(" Back ");
        jButton13_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton13_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13_13ActionPerformed(evt);
            }
        });

        jPanel33_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel38_38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38_38.setText("Employee ID");

        la.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laActionPerformed(evt);
            }
        });
        la.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                laKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                laKeyTyped(evt);
            }
        });

        jLabel23_23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23_23.setText("Name");

        la1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la1ActionPerformed(evt);
            }
        });
        la1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                la1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                la1KeyReleased(evt);
            }
        });

        jLabel39_39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel39_39.setText("Faculty");

        jLabel40_40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40_40.setText("Department");

        jLabel41_41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel41_41.setText("Center");

        jLabel42_42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel42_42.setText("Building");

        jLabel43_43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel43_43.setText("Level");

        la2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Home Science" }));

        la3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Software Engineering", "Infortmation Technology", "Computer Networks", "Interactive Media", "Civil Engineering", "Mechanical Engineering", "Electronic and Telecommuincation Engineering", "Humanities and Science", "Cyber Securrity", "Information System Engineering", "Mechatronic Engineering" }));

        la4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Center", "Malabe", "Matara", "Kandy", "Jaffna", "Metro", "Kurunegala" }));

        la5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building", "Main Building", "New Building", "Engeering", "Business", "D-Block" }));

        la6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));

        jLabel44_44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel44_44.setText("Rank");

        la7.setEditable(false);
        la7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        la7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                la7ActionPerformed(evt);
            }
        });
        la7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                la7KeyPressed(evt);
            }
        });

        jLabel45_45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45_45.setForeground(new java.awt.Color(255, 0, 51));
        jLabel45_45.setText("*Level.EmployeeID");

        jButton8_8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton8_8.setText(" Generate ");
        jButton8_8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8_8ActionPerformed(evt);
            }
        });

        jTable1_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Professor", "1"},
                {"Assistant Professor", "2"},
                {"Senior Lecturer (HG)", "3"},
                {"Senior Lecturer ", "4"},
                {"Lecturer", "5"},
                {"Assistant Lecturer", "6"},
                {"Instructor", "7"}
            },
            new String [] {
                "Category", "Level"
            }
        ));
        jScrollPane1_1.setViewportView(jTable1_1);

        javax.swing.GroupLayout jPanel33_33Layout = new javax.swing.GroupLayout(jPanel33_33);
        jPanel33_33.setLayout(jPanel33_33Layout);
        jPanel33_33Layout.setHorizontalGroup(
            jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33_33Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel33_33Layout.createSequentialGroup()
                        .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_33Layout.createSequentialGroup()
                                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39_39)
                                    .addComponent(jLabel23_23))
                                .addGap(142, 142, 142))
                            .addGroup(jPanel33_33Layout.createSequentialGroup()
                                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel40_40)
                                    .addComponent(jLabel38_38))
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_33Layout.createSequentialGroup()
                                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel42_42)
                                    .addComponent(jLabel43_43, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41_41, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(135, 135, 135)))
                        .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(la1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(la6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel33_33Layout.createSequentialGroup()
                        .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel33_33Layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel45_45, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel33_33Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel44_44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(la7, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton8_8)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel33_33Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel33_33Layout.setVerticalGroup(
            jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33_33Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38_38)
                    .addComponent(la, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23_23)
                    .addComponent(la1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39_39)
                    .addComponent(la2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40_40)
                    .addComponent(la3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41_41))
                .addGap(35, 35, 35)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(la5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42_42))
                .addGap(28, 28, 28)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43_43))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel33_33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(la7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44_44)
                    .addComponent(jButton8_8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel45_45)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout lecturer_add1Layout = new javax.swing.GroupLayout(lecturer_add1);
        lecturer_add1.setLayout(lecturer_add1Layout);
        lecturer_add1Layout.setHorizontalGroup(
            lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturer_add1Layout.createSequentialGroup()
                .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lecturer_add1Layout.createSequentialGroup()
                        .addGap(556, 556, 556)
                        .addComponent(jButton13_13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(adds_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lecturer_add1Layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jPanel33_33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lecturer_add1Layout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jPanel17_17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3409, Short.MAX_VALUE))
            .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_add1Layout.createSequentialGroup()
                    .addGap(1481, 1481, 1481)
                    .addComponent(jButton2_2)
                    .addContainerGap(2766, Short.MAX_VALUE)))
        );
        lecturer_add1Layout.setVerticalGroup(
            lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lecturer_add1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel17_17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel33_33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adds_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13_13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1111, Short.MAX_VALUE))
            .addGroup(lecturer_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_add1Layout.createSequentialGroup()
                    .addContainerGap(1666, Short.MAX_VALUE)
                    .addComponent(jButton2_2)
                    .addGap(266, 266, 266)))
        );

        javax.swing.GroupLayout lecturer_addLayout = new javax.swing.GroupLayout(lecturer_add);
        lecturer_add.setLayout(lecturer_addLayout);
        lecturer_addLayout.setHorizontalGroup(
            lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4450, Short.MAX_VALUE)
            .addGroup(lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_addLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        lecturer_addLayout.setVerticalGroup(
            lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(lecturer_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lecturer_addLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_add, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void adds_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adds_lecActionPerformed
        // TODO add your handling code here:

        int empId = Integer.parseInt(la.getText());
        String lecName = la1.getText();
        String lecFaculty = la2.getSelectedItem().toString();
        String lecDepartment = la3.getSelectedItem().toString();
        String lecCenter = la4.getSelectedItem().toString();
        String lecBulding = la5.getSelectedItem().toString();
        int lecLevel = Integer.parseInt(la6.getSelectedItem().toString());
        String lecRank = la7.getText();

        String id = la.getText();

        int length = id.length();

        try {

            //Check if there are any empty field before adding details to the database
            if (la.getText().isEmpty() || la1.getText().isEmpty() || la2.getSelectedItem().equals("Select Faculty") || la3.getSelectedItem().equals("Select Department") || la4.equals("Select Center") || la5.equals("Select Building") || la6.equals("Select Level") || la7.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Invalid Input");

            }

            //check if the employee ID contain six digits
            if (length < 6) {

                la.setEditable(true);
                JOptionPane.showMessageDialog(this, "Employee ID Should Contain Six Digits");

            } else {

                //add a new lecturer to the database
                Statement s = con.createStatement();
                s.execute("INSERT INTO lec(empID,name,faculty,dept,center,building,level,rank) values(" + empId + ",'" + lecName + "','" + lecFaculty + "','" + lecDepartment + "','" + lecCenter + "','" + lecBulding + "'," + lecLevel + ",'" + lecRank + "')");

                JOptionPane.showMessageDialog(this, "Records Are Submitted!");

                generator.setemployeeTable();
                s.close();
                generator.resetEmpData();

            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_adds_lecActionPerformed

    private void adds_lecKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_adds_lecKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_adds_lecKeyPressed

    private void jButton13_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13_13ActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturersPanel());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jButton13_13ActionPerformed

    private void laActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laActionPerformed

    private void laKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        String id = la.getText();

        int length = id.length();

        //check if this textField contain only numbers and backspace is allowed
        if (Character.isDigit(c) || Character.isISOControl(c)) {

            //check if the employee id contains six digits
            if (length < 6) {

                la.setEditable(true);

            } else {

                la.setEditable(false);

            }

        } else {

            la.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Numbers!");

        }
    }//GEN-LAST:event_laKeyPressed

    private void laKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_laKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_laKeyTyped

    private void la1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_la1ActionPerformed

    private void la1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la1KeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        //check if the textField contains only letters and space
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {

            la1.setEditable(true);

        } else {

            la1.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Letters!");

        }
    }//GEN-LAST:event_la1KeyPressed

    private void la1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_la1KeyReleased

    private void la7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_la7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_la7ActionPerformed

    private void la7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_la7KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_la7KeyPressed

    private void jButton8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_8ActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(la.getText());
        int level = Integer.parseInt(la6.getSelectedItem().toString());

        //concatenate the  values of level and id textfields
        String rank = level + "." + id;

        la7.setText("" + rank);
    }//GEN-LAST:event_jButton8_8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adds_lec;
    private javax.swing.JButton jButton13_13;
    private javax.swing.JButton jButton2_2;
    private javax.swing.JButton jButton8_8;
    private javax.swing.JLabel jLabel23_23;
    private javax.swing.JLabel jLabel38_38;
    private javax.swing.JLabel jLabel39_39;
    private javax.swing.JLabel jLabel40_40;
    private javax.swing.JLabel jLabel41_41;
    private javax.swing.JLabel jLabel42_42;
    private javax.swing.JLabel jLabel43_43;
    private javax.swing.JLabel jLabel44_44;
    private javax.swing.JLabel jLabel45_45;
    private javax.swing.JLabel jLabel46_46;
    private javax.swing.JPanel jPanel17_17;
    private javax.swing.JPanel jPanel33_33;
    private javax.swing.JScrollPane jScrollPane1_1;
    private javax.swing.JTable jTable1_1;
    public javax.swing.JTextField la;
    public javax.swing.JTextField la1;
    public javax.swing.JComboBox<String> la2;
    public javax.swing.JComboBox<String> la3;
    public javax.swing.JComboBox<String> la4;
    public javax.swing.JComboBox<String> la5;
    public javax.swing.JComboBox<String> la6;
    public javax.swing.JTextField la7;
    private javax.swing.JPanel lecturer_add;
    private javax.swing.JPanel lecturer_add1;
    // End of variables declaration//GEN-END:variables
}
