/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

/**
 *
 * @author Shakith
 */
public class lecturersPanel extends javax.swing.JPanel {

    Generator generator;
    
    /**
     * Creates new form lecturersPanel
     */
    public lecturersPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturersPanel = new javax.swing.JPanel();
        jPanel23_lecturersPanel = new javax.swing.JPanel();
        add_lec = new javax.swing.JButton();
        jLabel67_67 = new javax.swing.JLabel();
        jLabel27_lecturersPanel = new javax.swing.JLabel();
        jPanel24_lecturersPanel = new javax.swing.JPanel();
        lec_details = new javax.swing.JButton();
        jLabel66_66 = new javax.swing.JLabel();
        jLabel24_lecturersPanel = new javax.swing.JLabel();

        lecturersPanel.setBackground(new java.awt.Color(102, 51, 109));

        jPanel23_lecturersPanel.setBackground(new java.awt.Color(137, 14, 137));
        jPanel23_lecturersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        add_lec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_lec.setText("ADD NEW LECTURER");
        add_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_lecActionPerformed(evt);
            }
        });

        jLabel27_lecturersPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable/lecturers.png"))); // NOI18N

        javax.swing.GroupLayout jPanel23_lecturersPanelLayout = new javax.swing.GroupLayout(jPanel23_lecturersPanel);
        jPanel23_lecturersPanel.setLayout(jPanel23_lecturersPanelLayout);
        jPanel23_lecturersPanelLayout.setHorizontalGroup(
            jPanel23_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23_lecturersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel67_67)
                .addGap(88, 88, 88))
            .addGroup(jPanel23_lecturersPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(add_lec)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel23_lecturersPanelLayout.setVerticalGroup(
            jPanel23_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23_lecturersPanelLayout.createSequentialGroup()
                .addGroup(jPanel23_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23_lecturersPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel67_67, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23_lecturersPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel27_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(add_lec)
                .addGap(53, 53, 53))
        );

        jPanel24_lecturersPanel.setBackground(new java.awt.Color(137, 14, 137));
        jPanel24_lecturersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lec_details.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lec_details.setText("LECTURER DETAILS");
        lec_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lec_detailsActionPerformed(evt);
            }
        });

        jLabel24_lecturersPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/timetable/lecturers.png"))); // NOI18N

        javax.swing.GroupLayout jPanel24_lecturersPanelLayout = new javax.swing.GroupLayout(jPanel24_lecturersPanel);
        jPanel24_lecturersPanel.setLayout(jPanel24_lecturersPanelLayout);
        jPanel24_lecturersPanelLayout.setHorizontalGroup(
            jPanel24_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24_lecturersPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jPanel24_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lec_details)
                    .addGroup(jPanel24_lecturersPanelLayout.createSequentialGroup()
                        .addComponent(jLabel66_66)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel24_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66))
        );
        jPanel24_lecturersPanelLayout.setVerticalGroup(
            jPanel24_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24_lecturersPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel24_lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66_66, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(lec_details)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout lecturersPanelLayout = new javax.swing.GroupLayout(lecturersPanel);
        lecturersPanel.setLayout(lecturersPanelLayout);
        lecturersPanelLayout.setHorizontalGroup(
            lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturersPanelLayout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jPanel23_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jPanel24_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(3245, Short.MAX_VALUE))
        );
        lecturersPanelLayout.setVerticalGroup(
            lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturersPanelLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addGroup(lecturersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24_lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lecturersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lecturersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void add_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_lecActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturer_add());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_add_lecActionPerformed

    private void lec_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lec_detailsActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new view_lecturers());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_lec_detailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_lec;
    private javax.swing.JLabel jLabel24_lecturersPanel;
    private javax.swing.JLabel jLabel27_lecturersPanel;
    private javax.swing.JLabel jLabel66_66;
    private javax.swing.JLabel jLabel67_67;
    private javax.swing.JPanel jPanel23_lecturersPanel;
    private javax.swing.JPanel jPanel24_lecturersPanel;
    private javax.swing.JButton lec_details;
    private javax.swing.JPanel lecturersPanel;
    // End of variables declaration//GEN-END:variables
}
