/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shakith
 */
public class lecturer_edit extends javax.swing.JPanel {

    Generator generator;

    Connection con = null;

    /**
     * Creates new form lecturer_edit
     */
    public lecturer_edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturer_edit = new javax.swing.JPanel();
        update_lec = new javax.swing.JButton();
        jButton15_15 = new javax.swing.JButton();
        jPanel26_26 = new javax.swing.JPanel();
        jLabel78_78 = new javax.swing.JLabel();
        jPanel35_35 = new javax.swing.JPanel();
        jLabel83_83 = new javax.swing.JLabel();
        le = new javax.swing.JTextField();
        jLabel84_84 = new javax.swing.JLabel();
        jLabel85_85 = new javax.swing.JLabel();
        jLabel86_86 = new javax.swing.JLabel();
        le1 = new javax.swing.JTextField();
        le2 = new javax.swing.JComboBox<>();
        le3 = new javax.swing.JComboBox<>();
        jLabel87_87 = new javax.swing.JLabel();
        jLabel88_88 = new javax.swing.JLabel();
        jLabel89_89 = new javax.swing.JLabel();
        le4 = new javax.swing.JComboBox<>();
        le5 = new javax.swing.JComboBox<>();
        le6 = new javax.swing.JComboBox<>();
        jLabel76_76 = new javax.swing.JLabel();
        le7 = new javax.swing.JTextField();
        jLabel77_77 = new javax.swing.JLabel();
        jButton14_14 = new javax.swing.JButton();
        jScrollPane3_3 = new javax.swing.JScrollPane();
        jTable3_3 = new javax.swing.JTable();

        lecturer_edit.setBackground(new java.awt.Color(0, 0, 102));

        update_lec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_lec.setText(" Update Details ");
        update_lec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update_lec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_lecActionPerformed(evt);
            }
        });

        jButton15_15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton15_15.setText(" Back ");
        jButton15_15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton15_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15_15ActionPerformed(evt);
            }
        });

        jPanel26_26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26_26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel78_78.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel78_78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78_78.setText("EDIT LECTURER DETAILS");

        javax.swing.GroupLayout jPanel26_26Layout = new javax.swing.GroupLayout(jPanel26_26);
        jPanel26_26.setLayout(jPanel26_26Layout);
        jPanel26_26Layout.setHorizontalGroup(
            jPanel26_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26_26Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel78_78)
                .addGap(39, 39, 39))
        );
        jPanel26_26Layout.setVerticalGroup(
            jPanel26_26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26_26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel78_78)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel35_35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35_35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel83_83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel83_83.setText("Employee ID");

        le.setEditable(false);
        le.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le.setForeground(new java.awt.Color(102, 102, 102));
        le.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leActionPerformed(evt);
            }
        });
        le.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                leKeyPressed(evt);
            }
        });

        jLabel84_84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel84_84.setText("Name");

        jLabel85_85.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel85_85.setText("Faculty");

        jLabel86_86.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel86_86.setText("Department");

        le1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                le1ActionPerformed(evt);
            }
        });
        le1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                le1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                le1KeyReleased(evt);
            }
        });

        le2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Home Science" }));

        le3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Software Engineering", "Infortmation Technology", "Computer Networks", "Interactive Media", "Civil Engineering", "Mechanical Engineering", "Electronic and Telecommuincation Engineering", "Humanities and Science", "Cyber Securrity", "Information System Engineering", "Mechatronic Engineering" }));

        jLabel87_87.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel87_87.setText("Center");

        jLabel88_88.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel88_88.setText("Building");

        jLabel89_89.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel89_89.setText("Level");

        le4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Center", "Malabe", "Matara", "Kandy", "Jaffna", "Metro", "Kurunegala" }));

        le5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building", "Main Building", "New Building", "Engeering", "Business", "D-Block" }));
        le5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                le5ActionPerformed(evt);
            }
        });

        le6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));

        jLabel76_76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel76_76.setText("Rank");

        le7.setEditable(false);
        le7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        le7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                le7ActionPerformed(evt);
            }
        });

        jLabel77_77.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel77_77.setForeground(new java.awt.Color(255, 0, 51));
        jLabel77_77.setText("*Level.EmployeeID");

        jButton14_14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton14_14.setText(" Generate ");
        jButton14_14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14_14ActionPerformed(evt);
            }
        });

        jTable3_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Professor", "1"},
                {"Assistant Professor", "2"},
                {"Senior Lecturer (HG)", "3"},
                {"Senior Lecturer ", "4"},
                {"Lecturer", "5"},
                {"Assistant Lecturer", "6"},
                {"Instructor", "7"}
            },
            new String [] {
                "Category", "Level"
            }
        ));
        jScrollPane3_3.setViewportView(jTable3_3);

        javax.swing.GroupLayout jPanel35_35Layout = new javax.swing.GroupLayout(jPanel35_35);
        jPanel35_35.setLayout(jPanel35_35Layout);
        jPanel35_35Layout.setHorizontalGroup(
            jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35_35Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel35_35Layout.createSequentialGroup()
                        .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35_35Layout.createSequentialGroup()
                                .addComponent(jLabel83_83)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35_35Layout.createSequentialGroup()
                                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel86_86)
                                    .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel85_85)
                                        .addComponent(jLabel84_84))
                                    .addComponent(jLabel76_76))
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel77_77, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel35_35Layout.createSequentialGroup()
                                .addComponent(le7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14_14))))
                    .addGroup(jPanel35_35Layout.createSequentialGroup()
                        .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel88_88)
                            .addComponent(jLabel87_87)
                            .addComponent(jLabel89_89))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(le5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(le4, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(le3, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                            .addComponent(le2, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                            .addComponent(le, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(le1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(le6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35_35Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel35_35Layout.setVerticalGroup(
            jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35_35Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83_83))
                .addGap(37, 37, 37)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(le1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel84_84))
                .addGap(29, 29, 29)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(le2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel85_85))
                .addGap(31, 31, 31)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel86_86))
                .addGap(41, 41, 41)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel87_87)
                    .addComponent(le4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel88_88))
                .addGap(45, 45, 45)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(le6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel89_89))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel76_76, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35_35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(le7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton14_14)))
                .addGap(18, 18, 18)
                .addComponent(jLabel77_77)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout lecturer_editLayout = new javax.swing.GroupLayout(lecturer_edit);
        lecturer_edit.setLayout(lecturer_editLayout);
        lecturer_editLayout.setHorizontalGroup(
            lecturer_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturer_editLayout.createSequentialGroup()
                .addGroup(lecturer_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lecturer_editLayout.createSequentialGroup()
                        .addGap(601, 601, 601)
                        .addComponent(jButton15_15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(update_lec))
                    .addGroup(lecturer_editLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jPanel35_35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lecturer_editLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(jPanel26_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(3500, Short.MAX_VALUE))
        );
        lecturer_editLayout.setVerticalGroup(
            lecturer_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lecturer_editLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel26_26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel35_35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(lecturer_editLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15_15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_lec, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lecturer_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void update_lecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_lecActionPerformed
        // TODO add your handling code here:

        int empId = Integer.parseInt(le.getText());
        String lecName = le1.getText();
        String lecFaculty = le2.getSelectedItem().toString();
        String lecDepartment = le3.getSelectedItem().toString();
        String lecCenter = le4.getSelectedItem().toString();
        String lecBulding = le5.getSelectedItem().toString();
        int lecLevel = Integer.parseInt(le6.getSelectedItem().toString());
        String lecRank = le7.getText();

        try {

            //Check if there are any empty field before updating details
            if (le.getText().isEmpty() || le1.getText().isEmpty() || le2.getSelectedItem().equals("Select Faculty") || le3.getSelectedItem().equals("Select Department") || le4.equals("Select Center") || le5.equals("Select Building") || le6.equals("Select Level") || le7.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Invalid Input");

            }

            //update lecturer details
            Statement s = con.createStatement();
            s.execute("update lec set name='" + lecName + "',faculty='" + lecFaculty + "',dept = '" + lecDepartment + "',center = '" + lecCenter + "',building='" + lecBulding + "',level=" + lecLevel + ",rank='" + lecRank + "' where empID=" + empId);

            JOptionPane.showMessageDialog(this, "Records Are Updated!");

            generator.setemployeeTable();
            s.close();
            generator.resetEmpData();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Update Records!");

        }
    }//GEN-LAST:event_update_lecActionPerformed

    private void jButton15_15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15_15ActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new view_lecturers());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jButton15_15ActionPerformed

    private void leActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leActionPerformed

    private void leKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_leKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_leKeyPressed

    private void le1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_le1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_le1ActionPerformed

    private void le1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_le1KeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        //check if the textField contains only letters and space
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {

            le1.setEditable(true);

        } else {

            le1.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Letters!");

        }
    }//GEN-LAST:event_le1KeyPressed

    private void le1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_le1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_le1KeyReleased

    private void le5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_le5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_le5ActionPerformed

    private void le7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_le7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_le7ActionPerformed

    private void jButton14_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14_14ActionPerformed
        // TODO add your handling code here:

        int id = Integer.parseInt(le.getText());
        int level = Integer.parseInt(le6.getSelectedItem().toString());

        //concatenate the  values of level and id textfields
        String rank = level + "." + id;

        le7.setText("" + rank);
    }//GEN-LAST:event_jButton14_14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton14_14;
    private javax.swing.JButton jButton15_15;
    private javax.swing.JLabel jLabel76_76;
    private javax.swing.JLabel jLabel77_77;
    private javax.swing.JLabel jLabel78_78;
    private javax.swing.JLabel jLabel83_83;
    private javax.swing.JLabel jLabel84_84;
    private javax.swing.JLabel jLabel85_85;
    private javax.swing.JLabel jLabel86_86;
    private javax.swing.JLabel jLabel87_87;
    private javax.swing.JLabel jLabel88_88;
    private javax.swing.JLabel jLabel89_89;
    private javax.swing.JPanel jPanel26_26;
    private javax.swing.JPanel jPanel35_35;
    private javax.swing.JScrollPane jScrollPane3_3;
    private javax.swing.JTable jTable3_3;
    public javax.swing.JTextField le;
    public javax.swing.JTextField le1;
    public javax.swing.JComboBox<String> le2;
    public javax.swing.JComboBox<String> le3;
    public javax.swing.JComboBox<String> le4;
    public javax.swing.JComboBox<String> le5;
    public javax.swing.JComboBox<String> le6;
    public javax.swing.JTextField le7;
    private javax.swing.JPanel lecturer_edit;
    private javax.swing.JButton update_lec;
    // End of variables declaration//GEN-END:variables
}
