/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import DBconnetions.DBconnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class sessions_view extends javax.swing.JPanel {

    Generator generator;

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    session_edit edit;
    
    /**
     * Creates new form sessions_view
     */
    public sessions_view() {
        initComponents();       
        con = DBconnect.connect();
        sessionID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        panel111_viewSession = new javax.swing.JPanel();
        jLabel2_viewSession = new javax.swing.JLabel();
        jLabel3_viewSession = new javax.swing.JLabel();
        jLabel4_viewSession = new javax.swing.JLabel();
        jLabel5_viewSession = new javax.swing.JLabel();
        jLabel6_viewSession = new javax.swing.JLabel();
        jLabel7_viewSession = new javax.swing.JLabel();
        jLabel8_viewSession = new javax.swing.JLabel();
        jLabel9_viewSession = new javax.swing.JLabel();
        jLabel10_viewSession = new javax.swing.JLabel();
        tag_viewSession = new javax.swing.JComboBox<>();
        group1_viewSession = new javax.swing.JComboBox<>();
        group2_viewSession = new javax.swing.JComboBox<>();
        group_viewSession = new javax.swing.JTextField();
        sub_viewSession = new javax.swing.JComboBox<>();
        subName_viewSession = new javax.swing.JComboBox<>();
        subCode_viewSession = new javax.swing.JComboBox<>();
        students_viewSession = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        session_viewSession = new javax.swing.JTextArea();
        addGroup_viewSession = new javax.swing.JButton();
        generate_viewSession = new javax.swing.JButton();
        lecurersselect_viewSession = new javax.swing.JComboBox<>();
        select_viewSession = new javax.swing.JButton();
        jLabel11_viewSession = new javax.swing.JLabel();
        duration_viewSession = new javax.swing.JTextField();
        view_viewSession = new javax.swing.JButton();
        sessionId_viewSession = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturers_viewSession = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        lecturers_addSession1 = new javax.swing.JTextArea();
        edit_viewSession = new javax.swing.JButton();
        delete_viewSession = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 51, 109));

        jPanel7.setBackground(new java.awt.Color(102, 51, 109));

        panel111_viewSession.setBackground(new java.awt.Color(137, 14, 137));
        panel111_viewSession.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Session Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel111_viewSession.setToolTipText("Select");

        jLabel2_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_viewSession.setText("Lecturer(s)");

        jLabel3_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_viewSession.setText("Session ID");

        jLabel4_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_viewSession.setText("Group");

        jLabel5_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_viewSession.setText("Tag");

        jLabel6_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_viewSession.setText("Sub-group");

        jLabel7_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7_viewSession.setText("Subject Name");

        jLabel8_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8_viewSession.setText("Subject Code");

        jLabel9_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9_viewSession.setText("Student Count");

        jLabel10_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10_viewSession.setText("Session");

        tag_viewSession.setEditable(true);
        tag_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tag_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Tag" }));
        tag_viewSession.setBorder(null);
        tag_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_viewSessionActionPerformed(evt);
            }
        });

        group1_viewSession.setEditable(true);
        group1_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group1_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batch" }));
        group1_viewSession.setBorder(null);

        group2_viewSession.setEditable(true);
        group2_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group2_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Group" }));
        group2_viewSession.setBorder(null);

        group_viewSession.setEditable(false);
        group_viewSession.setBackground(new java.awt.Color(255, 255, 255));
        group_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_viewSessionActionPerformed(evt);
            }
        });

        sub_viewSession.setEditable(true);
        sub_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sub_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub-group" }));
        sub_viewSession.setBorder(null);

        subName_viewSession.setBackground(new java.awt.Color(204, 204, 204));
        subName_viewSession.setEditable(true);
        subName_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subName_viewSession.setForeground(new java.awt.Color(204, 204, 204));
        subName_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Name" }));
        subName_viewSession.setBorder(null);

        subCode_viewSession.setBackground(new java.awt.Color(204, 204, 204));
        subCode_viewSession.setEditable(true);
        subCode_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subCode_viewSession.setForeground(new java.awt.Color(204, 204, 204));
        subCode_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Code" }));
        subCode_viewSession.setBorder(null);

        students_viewSession.setEditable(false);
        students_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students_viewSession.setBorder(null);
        students_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_viewSessionActionPerformed(evt);
            }
        });

        session_viewSession.setEditable(false);
        session_viewSession.setBackground(new java.awt.Color(240, 240, 240));
        session_viewSession.setColumns(20);
        session_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        session_viewSession.setRows(5);
        session_viewSession.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(session_viewSession);

        addGroup_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addGroup_viewSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        addGroup_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroup_viewSessionActionPerformed(evt);
            }
        });

        generate_viewSession.setBackground(new java.awt.Color(102, 0, 102));
        generate_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generate_viewSession.setText("Generate Session");
        generate_viewSession.setBorder(null);
        generate_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_viewSessionActionPerformed(evt);
            }
        });

        lecurersselect_viewSession.setEditable(true);
        lecurersselect_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecurersselect_viewSession.setForeground(new java.awt.Color(240, 240, 240));
        lecurersselect_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lecturer" }));
        lecurersselect_viewSession.setBorder(null);
        lecurersselect_viewSession.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        select_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select_viewSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        select_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_viewSessionActionPerformed(evt);
            }
        });

        jLabel11_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11_viewSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11_viewSession.setText("Duration");

        duration_viewSession.setEditable(false);
        duration_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration_viewSession.setBorder(null);
        duration_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration_viewSessionActionPerformed(evt);
            }
        });

        view_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view_viewSession.setText("View");
        view_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_viewSessionActionPerformed(evt);
            }
        });

        sessionId_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sessionId_viewSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Session ID" }));
        sessionId_viewSession.setBorder(null);
        sessionId_viewSession.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lecturers_viewSession.setEditable(false);
        lecturers_viewSession.setBackground(new java.awt.Color(240, 240, 240));
        lecturers_viewSession.setColumns(20);
        lecturers_viewSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecturers_viewSession.setRows(5);
        lecturers_viewSession.setBorder(null);
        jScrollPane1.setViewportView(lecturers_viewSession);

        lecturers_addSession1.setEditable(false);
        lecturers_addSession1.setColumns(20);
        lecturers_addSession1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecturers_addSession1.setRows(5);
        lecturers_addSession1.setBorder(null);
        jScrollPane3.setViewportView(lecturers_addSession1);

        javax.swing.GroupLayout panel111_viewSessionLayout = new javax.swing.GroupLayout(panel111_viewSession);
        panel111_viewSession.setLayout(panel111_viewSessionLayout);
        panel111_viewSessionLayout.setHorizontalGroup(
            panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8_viewSession)
                                            .addComponent(jLabel7_viewSession))
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel5_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel4_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel9_viewSession)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11_viewSession)
                                            .addComponent(jLabel10_viewSession))
                                        .addGap(46, 46, 46)))))
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(students_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duration_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addComponent(group1_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(group2_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addGroup_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(group_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lecurersselect_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tag_viewSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subCode_viewSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subName_viewSession, javax.swing.GroupLayout.Alignment.LEADING, 0, 358, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(select_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                        .addComponent(sessionId_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(view_viewSession)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(generate_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
            .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                    .addContainerGap(397, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(378, 378, 378)))
        );
        panel111_viewSessionLayout.setVerticalGroup(
            panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sessionId_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(view_viewSession))
                        .addGap(21, 21, 21)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lecurersselect_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subName_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subCode_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addComponent(tag_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(group2_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(group1_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addGroup_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(group_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addComponent(jLabel5_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(students_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generate_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel111_viewSessionLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel10_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(858, 858, 858))
            .addGroup(panel111_viewSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_viewSessionLayout.createSequentialGroup()
                    .addContainerGap(703, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(683, 683, 683)))
        );

        edit_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_viewSession.setText("Edit");
        edit_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_viewSessionActionPerformed(evt);
            }
        });

        delete_viewSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_viewSession.setText("Delete");
        delete_viewSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_viewSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(panel111_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(edit_viewSession)
                .addGap(97, 97, 97)
                .addComponent(delete_viewSession)
                .addGap(549, 549, 549))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(panel111_viewSession, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_viewSession)
                    .addComponent(edit_viewSession))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tag_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_viewSessionActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tag_viewSessionActionPerformed

    private void group_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_viewSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_group_viewSessionActionPerformed

    private void students_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_viewSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_students_viewSessionActionPerformed

    private void addGroup_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroup_viewSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addGroup_viewSessionActionPerformed

    private void generate_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_viewSessionActionPerformed
        
    }//GEN-LAST:event_generate_viewSessionActionPerformed

    private void select_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_viewSessionActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_select_viewSessionActionPerformed

    private void duration_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration_viewSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duration_viewSessionActionPerformed

    private void view_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_viewSessionActionPerformed
        // TODO add your handling code here:
        
        FunctionSession f = new FunctionSession();
        
        ResultSet rs = null;

       
        String lecName = "lecturer";
        String subNames = "subName";
        String subCodes = "subCode";
        String tag = "tag";
        String group = "groupNo";
        String subgroup = "subgroupNo";
        String count = "students";
        String duration = "duration";
        String session = "sessions";        
                
        rs = f.find(sessionId_viewSession.getSelectedItem().toString());
        
        try {

            //view the details
            if (rs.next()) {
               
                lecturers_viewSession.setText(rs.getString("lecturer"));
                subName_viewSession.setSelectedItem(rs.getString("subName"));
                subCode_viewSession.setSelectedItem(rs.getString("subCode"));
                tag_viewSession.setSelectedItem(rs.getString("tag"));
                group_viewSession.setText(rs.getString("groupNo"));
                sub_viewSession.setSelectedItem(rs.getString("subgroupNo"));
                students_viewSession.setText(rs.getString("students"));
                duration_viewSession.setText(rs.getString("duration"));
                session_viewSession.setText(rs.getString("sessions"));
                
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, No Data Found!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_view_viewSessionActionPerformed

    private void edit_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_viewSessionActionPerformed
        // TODO add your handling code here:
        
        String sessionId = sessionId_viewSession.getSelectedItem().toString();
        String lecName = lecturers_viewSession.getText();
        String subNames = subName_viewSession.getSelectedItem().toString();
        String subCodes = subCode_viewSession.getSelectedItem().toString();
        String tag = tag_viewSession.getSelectedItem().toString();
        String group = group_viewSession.getText();
        String subgroup = sub_viewSession.getSelectedItem().toString();
        String count = students_viewSession.getText();
        String duration = duration_viewSession.getText();;
        String session = session_viewSession.getText();  
        
        generator.Parent.removeAll();
        generator.Parent.add(new session_edit(sessionId, lecName, subNames, subCodes, tag, group, subgroup, count, duration, session));
        generator.Parent.repaint();
        generator.Parent.revalidate();
       
    }//GEN-LAST:event_edit_viewSessionActionPerformed

    private void delete_viewSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_viewSessionActionPerformed
        // TODO add your handling code here:
        
        try {

            //delete session details from database
            String sessionId = sessionId_viewSession.getSelectedItem().toString();

            Statement s = con.createStatement();
            s.execute("delete from sessions where sessionID= '" + sessionId + "'");
            JOptionPane.showMessageDialog(this, "Record Are Deleted!");

            s.close();
            

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Delete Records!");
        }
    
    }//GEN-LAST:event_delete_viewSessionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup_viewSession;
    private javax.swing.JButton delete_viewSession;
    private javax.swing.JTextField duration_viewSession;
    private javax.swing.JButton edit_viewSession;
    private javax.swing.JButton generate_viewSession;
    private javax.swing.JComboBox<String> group1_viewSession;
    private javax.swing.JComboBox<String> group2_viewSession;
    private javax.swing.JTextField group_viewSession;
    private javax.swing.JLabel jLabel10_viewSession;
    private javax.swing.JLabel jLabel11_viewSession;
    private javax.swing.JLabel jLabel2_viewSession;
    private javax.swing.JLabel jLabel3_viewSession;
    private javax.swing.JLabel jLabel4_viewSession;
    private javax.swing.JLabel jLabel5_viewSession;
    private javax.swing.JLabel jLabel6_viewSession;
    private javax.swing.JLabel jLabel7_viewSession;
    private javax.swing.JLabel jLabel8_viewSession;
    private javax.swing.JLabel jLabel9_viewSession;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea lecturers_addSession1;
    private javax.swing.JTextArea lecturers_viewSession;
    private javax.swing.JComboBox<String> lecurersselect_viewSession;
    private javax.swing.JPanel panel111_viewSession;
    private javax.swing.JButton select_viewSession;
    private javax.swing.JComboBox<String> sessionId_viewSession;
    private javax.swing.JTextArea session_viewSession;
    private javax.swing.JTextField students_viewSession;
    private javax.swing.JComboBox<String> subCode_viewSession;
    private javax.swing.JComboBox<String> subName_viewSession;
    private javax.swing.JComboBox<String> sub_viewSession;
    private javax.swing.JComboBox<String> tag_viewSession;
    private javax.swing.JButton view_viewSession;
    // End of variables declaration//GEN-END:variables

private void sessionID(){      
        String sql = "select * from sessions";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                sessionId_viewSession.addItem(rs.getString("sessionID"));                
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }


 public class FunctionSession {

        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps = null;

        public ResultSet find(String s) {

            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "");
                ps = con.prepareStatement("select * from sessions where sessionID=?");
                ps.setString(1, s);
                rs = ps.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

            return rs;

        }

    }

}
