/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import DBconnetions.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class session_edit extends javax.swing.JPanel {

    Generator generator;
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String sessionID;
    String lecturer;
    String subName;
    String subCode;
    String tag;
    String groupNo;
    String subgroupNo;
    String students;
    String duration;
    String sessions;
    
    /**
     * Creates new form session_edit
     */
//    public session_edit() {
//    
//    }
    
    public session_edit(String sessionID, String lecturer, String subName, String subCode, String tag, String groupNo, String subgroupNo, String students, String duration, String sessions) {

        initComponents();
        con = DBconnect.connect();
        lecSessionedit();
        subNameSessionedit();
        subCodeSessionedit();
        tagSessionedit();
        group1edit();
        group2edit();
        sub2edit();

        this.sessionID = sessionID;
        this.lecturer = lecturer;
        this.subName = subName;
        this.subCode = subCode;
        this.tag = tag;
        this.groupNo = groupNo;
        this.subgroupNo = subgroupNo;
        this.students = students;
        this.duration = duration;
        this.sessions = sessions;

        getDetails();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel111_editSession = new javax.swing.JPanel();
        jLabel2_editSession = new javax.swing.JLabel();
        jLabel3_editSession = new javax.swing.JLabel();
        jLabel4_editSession = new javax.swing.JLabel();
        jLabel5_editSession = new javax.swing.JLabel();
        jLabel6_editSession = new javax.swing.JLabel();
        jLabel7_editSession = new javax.swing.JLabel();
        jLabel8_editSession = new javax.swing.JLabel();
        jLabel9_editSession = new javax.swing.JLabel();
        jLabel10_editSession = new javax.swing.JLabel();
        tag_editSession = new javax.swing.JComboBox<>();
        group1_editSession = new javax.swing.JComboBox<>();
        group2_editSession = new javax.swing.JComboBox<>();
        group_editSession = new javax.swing.JTextField();
        sub_editSession = new javax.swing.JComboBox<>();
        subName_editSession = new javax.swing.JComboBox<>();
        subCode_editSession = new javax.swing.JComboBox<>();
        students_editSession = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        session_editSession = new javax.swing.JTextArea();
        addGroup_editSession = new javax.swing.JButton();
        generate_editSession = new javax.swing.JButton();
        lecurersselect_editSession = new javax.swing.JComboBox<>();
        select_editSession = new javax.swing.JButton();
        jLabel11_editSession = new javax.swing.JLabel();
        duration_editSession = new javax.swing.JTextField();
        sessionId_editSession = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturers_editSession = new javax.swing.JTextArea();
        update_editSession = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 51, 109));

        panel111_editSession.setBackground(new java.awt.Color(137, 14, 137));
        panel111_editSession.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Session Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel111_editSession.setToolTipText("Select");

        jLabel2_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_editSession.setText("Lecturer(s)");

        jLabel3_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_editSession.setText("Session ID");

        jLabel4_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_editSession.setText("Group");

        jLabel5_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_editSession.setText("Tag");

        jLabel6_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6_editSession.setText("Sub-group");

        jLabel7_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7_editSession.setText("Subject Name");

        jLabel8_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8_editSession.setText("Subject Code");

        jLabel9_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9_editSession.setText("Student Count");

        jLabel10_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10_editSession.setText("Session");

        tag_editSession.setEditable(true);
        tag_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tag_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Tag" }));
        tag_editSession.setBorder(null);
        tag_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tag_editSessionActionPerformed(evt);
            }
        });

        group1_editSession.setEditable(true);
        group1_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group1_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Batch" }));
        group1_editSession.setBorder(null);

        group2_editSession.setEditable(true);
        group2_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        group2_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Group" }));
        group2_editSession.setBorder(null);

        group_editSession.setEditable(false);
        group_editSession.setBackground(new java.awt.Color(255, 255, 255));
        group_editSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        group_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                group_editSessionActionPerformed(evt);
            }
        });

        sub_editSession.setEditable(true);
        sub_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sub_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sub-group" }));
        sub_editSession.setBorder(null);

        subName_editSession.setBackground(new java.awt.Color(204, 204, 204));
        subName_editSession.setEditable(true);
        subName_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subName_editSession.setForeground(new java.awt.Color(204, 204, 204));
        subName_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Name" }));
        subName_editSession.setBorder(null);

        subCode_editSession.setBackground(new java.awt.Color(204, 204, 204));
        subCode_editSession.setEditable(true);
        subCode_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subCode_editSession.setForeground(new java.awt.Color(204, 204, 204));
        subCode_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject Code" }));
        subCode_editSession.setBorder(null);

        students_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        students_editSession.setBorder(null);
        students_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                students_editSessionActionPerformed(evt);
            }
        });

        session_editSession.setEditable(false);
        session_editSession.setColumns(20);
        session_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        session_editSession.setRows(5);
        session_editSession.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(session_editSession);

        addGroup_editSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addGroup_editSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        addGroup_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroup_editSessionActionPerformed(evt);
            }
        });

        generate_editSession.setBackground(new java.awt.Color(102, 0, 102));
        generate_editSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generate_editSession.setText("Generate Session");
        generate_editSession.setBorder(null);
        generate_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_editSessionActionPerformed(evt);
            }
        });

        lecurersselect_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecurersselect_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Lecturer" }));
        lecurersselect_editSession.setBorder(null);
        lecurersselect_editSession.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        select_editSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        select_editSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/plus_icon.png"))); // NOI18N
        select_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_editSessionActionPerformed(evt);
            }
        });

        jLabel11_editSession.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11_editSession.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11_editSession.setText("Duration");

        duration_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration_editSession.setBorder(null);
        duration_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duration_editSessionActionPerformed(evt);
            }
        });

        sessionId_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sessionId_editSession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Session ID" }));
        sessionId_editSession.setBorder(null);
        sessionId_editSession.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lecturers_editSession.setEditable(false);
        lecturers_editSession.setColumns(20);
        lecturers_editSession.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lecturers_editSession.setRows(5);
        lecturers_editSession.setBorder(null);
        jScrollPane1.setViewportView(lecturers_editSession);

        javax.swing.GroupLayout panel111_editSessionLayout = new javax.swing.GroupLayout(panel111_editSession);
        panel111_editSession.setLayout(panel111_editSessionLayout);
        panel111_editSessionLayout.setHorizontalGroup(
            panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8_editSession)
                                            .addComponent(jLabel7_editSession))
                                        .addGap(23, 23, 23))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel5_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel9_editSession)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11_editSession)
                                            .addComponent(jLabel10_editSession))
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                                        .addComponent(jLabel4_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)))))
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lecurersselect_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tag_editSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subCode_editSession, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(subName_editSession, javax.swing.GroupLayout.Alignment.LEADING, 0, 358, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(select_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sessionId_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(students_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sub_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duration_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                        .addComponent(group1_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(group2_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(addGroup_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(group_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(generate_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        panel111_editSessionLayout.setVerticalGroup(
            panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel111_editSessionLayout.createSequentialGroup()
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sessionId_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(select_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lecurersselect_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subName_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subCode_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                        .addComponent(tag_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(group2_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(group1_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addGroup_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel111_editSessionLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(group_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                        .addComponent(jLabel5_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(students_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(duration_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generate_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(panel111_editSessionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel111_editSessionLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel10_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(852, 852, 852))
        );

        update_editSession.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update_editSession.setText("Update");
        update_editSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_editSessionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(panel111_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(610, 610, 610)
                        .addComponent(update_editSession)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(panel111_editSession, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_editSession)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tag_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tag_editSessionActionPerformed
        // TODO add your handling code here:

        String id = tag_editSession.getSelectedItem().toString();

            if (id.equals("practical")) {

               sub_editSession.setEnabled(true);

            } 
            else {

               sub_editSession.setEnabled(false);

            }
            
    }//GEN-LAST:event_tag_editSessionActionPerformed

    private void group_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_group_editSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_group_editSessionActionPerformed

    private void students_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_students_editSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_students_editSessionActionPerformed

    private void addGroup_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroup_editSessionActionPerformed
        // TODO add your handling code here:
        
        String group1 = group1_editSession.getSelectedItem().toString();
        String group2 = group2_editSession.getSelectedItem().toString();

        String group = group1 + "." + group2;

        group_editSession.setText(group);
        
    }//GEN-LAST:event_addGroup_editSessionActionPerformed

    private void generate_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_editSessionActionPerformed

        String lecturer = lecturers_editSession.getText();
        String subName = subName_editSession.getSelectedItem().toString();
        String subCode = subCode_editSession.getSelectedItem().toString();
        String tag = tag_editSession.getSelectedItem().toString();
        String group = group_editSession.getText();
        String subgroup = sub_editSession.getSelectedItem().toString();
        int count = Integer.parseInt(students_editSession.getText());
        String duration = duration_editSession.getText();;
        String sessions = session_editSession.getText();  
        
        //set the update details
        String session = lecturer  + "\n" + subName + "\n" + subCode + "\n" + tag + "\n" + group + "\n" + subgroup + "" + "\n" + count + "(" + duration + ")";
               
       session_editSession.setText(session);
               
    }//GEN-LAST:event_generate_editSessionActionPerformed

    private void select_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_editSessionActionPerformed
        // TODO add your handling code here:
        
        //add one or more lecturers
        lecturers_editSession.setText(lecturers_editSession.getText()+lecurersselect_editSession.getSelectedItem().toString()+",");  
        
    }//GEN-LAST:event_select_editSessionActionPerformed

    private void duration_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duration_editSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duration_editSessionActionPerformed

    private void update_editSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_editSessionActionPerformed
        // TODO add your handling code here:
        
        String sessionId = sessionId_editSession.getSelectedItem().toString();
        String lecName = lecturers_editSession.getText();
        String subNames = subName_editSession.getSelectedItem().toString();
        String subCodes = subCode_editSession.getSelectedItem().toString();
        String tag = tag_editSession.getSelectedItem().toString();
        String group = group_editSession.getText();
        String subgroup = sub_editSession.getSelectedItem().toString();
        int count = Integer.parseInt(students_editSession.getText());
        String duration = duration_editSession.getText();;
        String sessions = session_editSession.getText();  

        try {

            //Check if there are any empty field before updating details
            if (lecturers_editSession.getText().isEmpty() || subName_editSession.getSelectedItem().equals("Select Subject Name") || subCode_editSession.getSelectedItem().equals("Select Subject Code") || tag_editSession.getSelectedItem().equals("Select Tag") || group_editSession.getText().isEmpty() || sub_editSession.getSelectedItem().equals("Select Sub-group") || students_editSession.getText().isEmpty() || duration_editSession.getText().isEmpty() || session_editSession.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Invalid Input");

            }

            //update session details
            Statement s = con.createStatement();
            s.execute("update sessions set lecturer='" + lecName + "',tag='" + tag + "',groupNo = '" + group + "',subgroupNo = '" + subgroup + "',subName='" + subNames + "',subCode='" + subCodes + "',students=" + count + ",duration ='" + duration + "',sessions ='" + sessions + "' where sessionID= '" + sessionId + "'");

            JOptionPane.showMessageDialog(this, "Records Are Updated!");

            

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Update Records!");

        }
    }//GEN-LAST:event_update_editSessionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroup_editSession;
    private javax.swing.JTextField duration_editSession;
    private javax.swing.JButton generate_editSession;
    private javax.swing.JComboBox<String> group1_editSession;
    private javax.swing.JComboBox<String> group2_editSession;
    private javax.swing.JTextField group_editSession;
    private javax.swing.JLabel jLabel10_editSession;
    private javax.swing.JLabel jLabel11_editSession;
    private javax.swing.JLabel jLabel2_editSession;
    private javax.swing.JLabel jLabel3_editSession;
    private javax.swing.JLabel jLabel4_editSession;
    private javax.swing.JLabel jLabel5_editSession;
    private javax.swing.JLabel jLabel6_editSession;
    private javax.swing.JLabel jLabel7_editSession;
    private javax.swing.JLabel jLabel8_editSession;
    private javax.swing.JLabel jLabel9_editSession;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea lecturers_editSession;
    private javax.swing.JComboBox<String> lecurersselect_editSession;
    private javax.swing.JPanel panel111_editSession;
    private javax.swing.JButton select_editSession;
    private javax.swing.JComboBox<String> sessionId_editSession;
    private javax.swing.JTextArea session_editSession;
    private javax.swing.JTextField students_editSession;
    private javax.swing.JComboBox<String> subCode_editSession;
    private javax.swing.JComboBox<String> subName_editSession;
    private javax.swing.JComboBox<String> sub_editSession;
    private javax.swing.JComboBox<String> tag_editSession;
    private javax.swing.JButton update_editSession;
    // End of variables declaration//GEN-END:variables

public void getDetails() {
    
        sessionId_editSession.setSelectedItem(sessionID);
        lecturers_editSession.setText(lecturer);
        subName_editSession.setSelectedItem(subName);
        subCode_editSession.setSelectedItem(subCode);
        tag_editSession.setSelectedItem(tag);
        group_editSession.setText(groupNo);
        sub_editSession.setSelectedItem(subgroupNo);
        students_editSession.setText(students);
        duration_editSession.setText(duration);
        session_editSession.setText(sessions);
       
    }

private void lecSessionedit(){      
        String sql = "select * from lec";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                lecurersselect_editSession.addItem(rs.getString("name"));                
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void subNameSessionedit(){      
        String sql = "select * from subject";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                subName_editSession.addItem(rs.getString("name"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void subCodeSessionedit(){      
        String sql = "select * from subject";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                subCode_editSession.addItem(rs.getString("code"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void tagSessionedit(){      
        
    String sql = "select * from tag";  
        
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                tag_editSession.addItem(rs.getString("tag"));   
            }         }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void group1edit(){      
        String sql = "select * from groups";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                group1_editSession.addItem(rs.getString("batch"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void group2edit(){      
        String sql = "select * from groups";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                group2_editSession.addItem(rs.getString("groups"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }

private void sub2edit(){      
        String sql = "select * from subgroup";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                sub_editSession.addItem(rs.getString("sub_group"));              
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }



}
