/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shakith
 */
public class view_lecturers extends javax.swing.JPanel {

    Generator generator;

    Connection con = null;
    lecturer_edit edit;

    /**
     * Creates new form view_lecturers
     */
    public view_lecturers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_lecturers = new javax.swing.JPanel();
        jLabel60_60 = new javax.swing.JLabel();
        jLabel62_62 = new javax.swing.JLabel();
        jLabel59_59 = new javax.swing.JLabel();
        jLabel64_64 = new javax.swing.JLabel();
        jLabel58_58 = new javax.swing.JLabel();
        jLabel61_61 = new javax.swing.JLabel();
        jLabel63_63 = new javax.swing.JLabel();
        jLabel57_57 = new javax.swing.JLabel();
        jPanel18_18 = new javax.swing.JPanel();
        jLabel47_47 = new javax.swing.JLabel();
        jButton9_9 = new javax.swing.JButton();
        jTextField8_8 = new javax.swing.JTextField();
        jTextField9_9 = new javax.swing.JTextField();
        jComboBox11_11 = new javax.swing.JComboBox<>();
        jComboBox12_12 = new javax.swing.JComboBox<>();
        jComboBox13_13 = new javax.swing.JComboBox<>();
        jComboBox14_14 = new javax.swing.JComboBox<>();
        jComboBox15_15 = new javax.swing.JComboBox<>();
        jTextField10_10 = new javax.swing.JTextField();
        edit_lec1 = new javax.swing.JButton();
        delete_lec1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        edit_lecs = new javax.swing.JButton();
        delete_lecs = new javax.swing.JButton();
        jPanel25_25 = new javax.swing.JPanel();
        jLabel75_75 = new javax.swing.JLabel();
        jPanel34_34 = new javax.swing.JPanel();
        jLabel65_65 = new javax.swing.JLabel();
        lds = new javax.swing.JTextField();
        jLabel68_68 = new javax.swing.JLabel();
        jLabel69_69 = new javax.swing.JLabel();
        ld2 = new javax.swing.JComboBox<>();
        jLabel70_70 = new javax.swing.JLabel();
        ld3 = new javax.swing.JComboBox<>();
        jLabel71_71 = new javax.swing.JLabel();
        ld4 = new javax.swing.JComboBox<>();
        jLabel72_72 = new javax.swing.JLabel();
        ld5 = new javax.swing.JComboBox<>();
        jLabel73_73 = new javax.swing.JLabel();
        ld6 = new javax.swing.JComboBox<>();
        jLabel74_74 = new javax.swing.JLabel();
        ld7 = new javax.swing.JTextField();
        view_lecs = new javax.swing.JButton();
        jButton11_11 = new javax.swing.JButton();
        ld1 = new javax.swing.JTextField();
        ld = new javax.swing.JTextField();
        jScrollPane2_2 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();

        view_lecturers.setBackground(new java.awt.Color(0, 0, 102));

        jLabel60_60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60_60.setText("Department");

        jLabel62_62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel62_62.setText("Building");

        jLabel59_59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59_59.setText("Faculty");

        jLabel64_64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64_64.setText("Rank");

        jLabel58_58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58_58.setText("Name");

        jLabel61_61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel61_61.setText("Center");

        jLabel63_63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel63_63.setText("Level");

        jLabel57_57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57_57.setText("Employee ID");

        jPanel18_18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18_18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel47_47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47_47.setText("Lecturer Details");

        javax.swing.GroupLayout jPanel18_18Layout = new javax.swing.GroupLayout(jPanel18_18);
        jPanel18_18.setLayout(jPanel18_18Layout);
        jPanel18_18Layout.setHorizontalGroup(
            jPanel18_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18_18Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel47_47)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel18_18Layout.setVerticalGroup(
            jPanel18_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18_18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47_47)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton9_9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9_9.setText(" Back ");
        jButton9_9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton9_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9_9ActionPerformed(evt);
            }
        });

        jTextField8_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8_8ActionPerformed(evt);
            }
        });

        jTextField9_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9_9ActionPerformed(evt);
            }
        });

        jComboBox11_11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox12_12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox13_13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox14_14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox15_15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField10_10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10_10.setForeground(new java.awt.Color(204, 204, 204));
        jTextField10_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10_10ActionPerformed(evt);
            }
        });

        edit_lec1.setBackground(new java.awt.Color(255, 255, 255));
        edit_lec1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_lec1.setText(" Edit ");
        edit_lec1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        edit_lec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_lec1ActionPerformed(evt);
            }
        });

        delete_lec1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_lec1.setText(" Delete ");
        delete_lec1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton10.setText(" Generate ");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setEnabled(false);

        edit_lecs.setBackground(new java.awt.Color(255, 255, 255));
        edit_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_lecs.setText(" Edit ");
        edit_lecs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        edit_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_lecsActionPerformed(evt);
            }
        });

        delete_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_lecs.setText(" Delete ");
        delete_lecs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        delete_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_lecsActionPerformed(evt);
            }
        });

        jPanel25_25.setBackground(new java.awt.Color(0, 0, 0));
        jPanel25_25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel75_75.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel75_75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75_75.setText("LECTURER DETAILS");

        javax.swing.GroupLayout jPanel25_25Layout = new javax.swing.GroupLayout(jPanel25_25);
        jPanel25_25.setLayout(jPanel25_25Layout);
        jPanel25_25Layout.setHorizontalGroup(
            jPanel25_25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25_25Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel75_75)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel25_25Layout.setVerticalGroup(
            jPanel25_25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25_25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel75_75)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel34_34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34_34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel65_65.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel65_65.setText("Employee ID");

        lds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lds.setForeground(new java.awt.Color(102, 102, 102));
        lds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ldsKeyPressed(evt);
            }
        });

        jLabel68_68.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel68_68.setText("Name");

        jLabel69_69.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel69_69.setText("Faculty");

        ld2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld2.setForeground(new java.awt.Color(102, 102, 102));
        ld2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Home Science" }));

        jLabel70_70.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel70_70.setText("Department");

        ld3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld3.setForeground(new java.awt.Color(102, 102, 102));
        ld3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Software Engineering", "Infortmation Technology", "Computer Networks", "Interactive Media", "Civil Engineering", "Mechanical Engineering", "Electronic and Telecommuincation Engineering", "Humanities and Science", "Cyber Securrity", "Information System Engineering", "Mechatronic Engineering" }));

        jLabel71_71.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel71_71.setText("Center");

        ld4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld4.setForeground(new java.awt.Color(102, 102, 102));
        ld4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Center", "Malabe", "Matara", "Kandy", "Jaffna", "Metro", "Kurunegala" }));

        jLabel72_72.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel72_72.setText("Building");

        ld5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld5.setForeground(new java.awt.Color(102, 102, 102));
        ld5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building", "Main Building", "New Building", "Engeering", "Business", "D-Block" }));

        jLabel73_73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel73_73.setText("Level");

        ld6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld6.setForeground(new java.awt.Color(102, 102, 102));
        ld6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));

        jLabel74_74.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel74_74.setText("Rank");

        ld7.setEditable(false);
        ld7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld7.setForeground(new java.awt.Color(102, 102, 102));
        ld7.setEnabled(false);
        ld7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ld7ActionPerformed(evt);
            }
        });

        view_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view_lecs.setText(" View ");
        view_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_lecsActionPerformed(evt);
            }
        });

        jButton11_11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton11_11.setText(" Generate ");
        jButton11_11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11_11.setEnabled(false);

        ld1.setEditable(false);
        ld1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld1.setForeground(new java.awt.Color(102, 102, 102));
        ld1.setEnabled(false);
        ld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ld1ActionPerformed(evt);
            }
        });
        ld1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ld1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34_34Layout = new javax.swing.GroupLayout(jPanel34_34);
        jPanel34_34.setLayout(jPanel34_34Layout);
        jPanel34_34Layout.setHorizontalGroup(
            jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34_34Layout.createSequentialGroup()
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34_34Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70_70)
                            .addComponent(jLabel65_65)
                            .addGroup(jPanel34_34Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel71_71)
                                    .addComponent(jLabel73_73)
                                    .addComponent(jLabel72_72)))
                            .addGroup(jPanel34_34Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel68_68)
                                    .addComponent(jLabel69_69))))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ld5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ld2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ld3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ld4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel34_34Layout.createSequentialGroup()
                                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ld7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ld6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lds, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton11_11)
                                    .addComponent(view_lecs)))
                            .addComponent(ld1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel34_34Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel74_74)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel34_34Layout.setVerticalGroup(
            jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34_34Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_lecs)
                    .addComponent(lds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65_65))
                .addGap(38, 38, 38)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68_68)
                    .addComponent(ld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69_69))
                .addGap(58, 58, 58)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel70_70)
                    .addComponent(ld3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71_71))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72_72))
                .addGap(61, 61, 61)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73_73))
                .addGap(56, 56, 56)
                .addGroup(jPanel34_34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11_11)
                    .addComponent(jLabel74_74))
                .addGap(63, 63, 63))
        );

        ld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldActionPerformed(evt);
            }
        });

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2_2.setViewportView(employeeTable);

        javax.swing.GroupLayout view_lecturersLayout = new javax.swing.GroupLayout(view_lecturers);
        view_lecturers.setLayout(view_lecturersLayout);
        view_lecturersLayout.setHorizontalGroup(
            view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jButton9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(edit_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(delete_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(828, 828, 828)
                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2834, Short.MAX_VALUE)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel59_59)
                                            .addComponent(jLabel58_58))
                                        .addGap(116, 116, 116))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel61_61)
                                        .addGap(115, 115, 115))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel60_60)
                                        .addGap(93, 93, 93))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel57_57)
                                        .addGap(76, 76, 76)))
                                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox13_13, javax.swing.GroupLayout.Alignment.TRAILING, 0, 184, Short.MAX_VALUE)
                                    .addComponent(jComboBox12_12, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox11_11, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField9_9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField8_8, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel62_62)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox14_14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel63_63)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox15_15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel64_64)
                                    .addGap(117, 117, 117)
                                    .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_lecturersLayout.createSequentialGroup()
                                            .addComponent(edit_lec1)
                                            .addGap(53, 53, 53)
                                            .addComponent(delete_lec1))
                                        .addComponent(jTextField10_10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(55, 55, 55)
                .addComponent(jButton10)
                .addGap(101, 101, 101))
            .addGroup(view_lecturersLayout.createSequentialGroup()
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jPanel34_34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jPanel25_25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view_lecturersLayout.setVerticalGroup(
            view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_lecturersLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel25_25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel34_34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jScrollPane2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9_9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57_57))
                .addGap(18, 18, 18)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58_58))
                .addGap(38, 38, 38)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox11_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59_59))
                .addGap(27, 27, 27)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox12_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60_60))
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox13_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61_61)))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox14_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62_62))
                .addGap(33, 33, 33)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox15_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63_63))
                .addGap(44, 44, 44)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jLabel64_64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_lec1)
                    .addComponent(delete_lec1))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(view_lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(view_lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9_9ActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturersPanel());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jButton9_9ActionPerformed

    private void jTextField8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_8ActionPerformed

    private void jTextField9_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9_9ActionPerformed

    private void jTextField10_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_10ActionPerformed

    private void edit_lec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_lec1ActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturer_edit());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_edit_lec1ActionPerformed

    private void edit_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_lecsActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturer_edit());
        generator.Parent.repaint();
        generator.Parent.revalidate();

        Functionlec f = new Functionlec();

        ResultSet rs = null;

        String lecName = "empID";
        String lecFaculty = "faculty";
        String lecDepartment = "dept";
        String lecCenter = "center";
        String lecBulding = "building";
        String lecLevel = "level";
        String lecRank = "rank";

        rs = f.find(lds.getText());

        try {

            if (rs.next()) {

                edit.le.setText(rs.getString("empID"));
                edit.le1.setText(rs.getString("name"));
                edit.le2.setSelectedItem(rs.getString("faculty"));
                edit.le3.setSelectedItem(rs.getString("dept"));
                edit.le4.setSelectedItem(rs.getString("center"));
                edit.le5.setSelectedItem(rs.getString("building"));
                edit.le6.setSelectedItem(rs.getString("level"));
                edit.le7.setText(rs.getString("rank"));
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, No Data Found!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_edit_lecsActionPerformed

    private void delete_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_lecsActionPerformed
        // TODO add your handling code here:

        try {

            //delete lecturer details from database
            int empId = Integer.parseInt(lds.getText());

            Statement s = con.createStatement();
            s.execute("delete from lec where empID=" + empId);
            JOptionPane.showMessageDialog(this, "Record Are Deleted!");

            generator.setemployeeTable();
            s.close();
            generator.resetEmpData();

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Delete Records!");
        }
    }//GEN-LAST:event_delete_lecsActionPerformed

    private void ldsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ldsKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();
        String id = lds.getText();

        int length = id.length();

        if (Character.isDigit(c) || Character.isISOControl(c)) {

            if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '5') {

                if (length < 6) {

                    lds.setEditable(true);

                } else {

                    lds.setEditable(false);

                }

            }

        } else {

            lds.setEditable(false);
            JOptionPane.showMessageDialog(this, "Enter Only Numbers!");

        }
    }//GEN-LAST:event_ldsKeyPressed

    private void ld7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ld7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld7ActionPerformed

    private void view_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_lecsActionPerformed
        // TODO add your handling code here:

        Functionlec f = new Functionlec();

        ResultSet rs = null;

        String lecName = "empID";
        String lecFaculty = "faculty";
        String lecDepartment = "dept";
        String lecCenter = "center";
        String lecBulding = "building";
        String lecLevel = "level";
        String lecRank = "rank";

        rs = f.find(lds.getText());

        try {

            //view the details
            if (rs.next()) {

                ld1.setText(rs.getString("name"));
                ld2.setSelectedItem(rs.getString("faculty"));
                ld3.setSelectedItem(rs.getString("dept"));
                ld4.setSelectedItem(rs.getString("center"));
                ld5.setSelectedItem(rs.getString("building"));
                ld6.setSelectedItem(rs.getString("level"));
                ld7.setText(rs.getString("rank"));
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, No Data Found!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_view_lecsActionPerformed

    private void ld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld1ActionPerformed

    private void ld1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ld1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld1KeyPressed

    private void ldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_lec1;
    private javax.swing.JButton delete_lecs;
    private javax.swing.JButton edit_lec1;
    private javax.swing.JButton edit_lecs;
    public javax.swing.JTable employeeTable;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11_11;
    private javax.swing.JButton jButton9_9;
    private javax.swing.JComboBox<String> jComboBox11_11;
    private javax.swing.JComboBox<String> jComboBox12_12;
    private javax.swing.JComboBox<String> jComboBox13_13;
    private javax.swing.JComboBox<String> jComboBox14_14;
    private javax.swing.JComboBox<String> jComboBox15_15;
    private javax.swing.JLabel jLabel47_47;
    private javax.swing.JLabel jLabel57_57;
    private javax.swing.JLabel jLabel58_58;
    private javax.swing.JLabel jLabel59_59;
    private javax.swing.JLabel jLabel60_60;
    private javax.swing.JLabel jLabel61_61;
    private javax.swing.JLabel jLabel62_62;
    private javax.swing.JLabel jLabel63_63;
    private javax.swing.JLabel jLabel64_64;
    private javax.swing.JLabel jLabel65_65;
    private javax.swing.JLabel jLabel68_68;
    private javax.swing.JLabel jLabel69_69;
    private javax.swing.JLabel jLabel70_70;
    private javax.swing.JLabel jLabel71_71;
    private javax.swing.JLabel jLabel72_72;
    private javax.swing.JLabel jLabel73_73;
    private javax.swing.JLabel jLabel74_74;
    private javax.swing.JLabel jLabel75_75;
    private javax.swing.JPanel jPanel18_18;
    private javax.swing.JPanel jPanel25_25;
    private javax.swing.JPanel jPanel34_34;
    private javax.swing.JScrollPane jScrollPane2_2;
    private javax.swing.JTextField jTextField10_10;
    private javax.swing.JTextField jTextField8_8;
    private javax.swing.JTextField jTextField9_9;
    private javax.swing.JTextField ld;
    private javax.swing.JTextField ld1;
    private javax.swing.JComboBox<String> ld2;
    private javax.swing.JComboBox<String> ld3;
    private javax.swing.JComboBox<String> ld4;
    private javax.swing.JComboBox<String> ld5;
    private javax.swing.JComboBox<String> ld6;
    private javax.swing.JTextField ld7;
    private javax.swing.JTextField lds;
    private javax.swing.JButton view_lecs;
    private javax.swing.JPanel view_lecturers;
    // End of variables declaration//GEN-END:variables

    public class Functionlec {

        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps = null;

        public ResultSet find(String s) {

            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3307/timetable", "root", "123");
                ps = con.prepareStatement("select * from lec where empID=?");
                ps.setString(1, s);
                rs = ps.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

            return rs;

        }

    }
}
