/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import DBconnetions.DBconnect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Shakith
 */
public class view_lecturers extends javax.swing.JPanel {

    Generator generator;

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    lecturer_edit edit;
    

    /**
     * Creates new form view_lecturers
     */
    public view_lecturers() {
        initComponents();
        con = DBconnect.connect();
        lecturerSearch();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view_lecturers = new javax.swing.JPanel();
        jLabel60_60 = new javax.swing.JLabel();
        jLabel62_62 = new javax.swing.JLabel();
        jLabel59_59 = new javax.swing.JLabel();
        jLabel64_64 = new javax.swing.JLabel();
        jLabel58_58 = new javax.swing.JLabel();
        jLabel61_61 = new javax.swing.JLabel();
        jLabel63_63 = new javax.swing.JLabel();
        jLabel57_57 = new javax.swing.JLabel();
        jPanel18_18 = new javax.swing.JPanel();
        jLabel47_47 = new javax.swing.JLabel();
        jButton9__viewlec = new javax.swing.JButton();
        jTextField8_8 = new javax.swing.JTextField();
        jTextField9_9 = new javax.swing.JTextField();
        jComboBox11_11 = new javax.swing.JComboBox<>();
        jComboBox12_12 = new javax.swing.JComboBox<>();
        jComboBox13_13 = new javax.swing.JComboBox<>();
        jComboBox14_14 = new javax.swing.JComboBox<>();
        jComboBox15_15 = new javax.swing.JComboBox<>();
        jTextField10_10 = new javax.swing.JTextField();
        edit_lec1 = new javax.swing.JButton();
        delete_lec1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        edit_lecs = new javax.swing.JButton();
        delete_lecs = new javax.swing.JButton();
        jPanel34_viewlec = new javax.swing.JPanel();
        jLabel65_viewlec = new javax.swing.JLabel();
        jLabel68_viewlec = new javax.swing.JLabel();
        jLabel69_viewlec = new javax.swing.JLabel();
        ld2 = new javax.swing.JComboBox<>();
        jLabel70_viewlec = new javax.swing.JLabel();
        ld3 = new javax.swing.JComboBox<>();
        jLabel71_viewlec = new javax.swing.JLabel();
        ld4 = new javax.swing.JComboBox<>();
        jLabel72_viewlec = new javax.swing.JLabel();
        ld5 = new javax.swing.JComboBox<>();
        jLabel73_viewlec = new javax.swing.JLabel();
        ld6 = new javax.swing.JComboBox<>();
        jLabel74_viewlec = new javax.swing.JLabel();
        ld7 = new javax.swing.JTextField();
        view_lecs = new javax.swing.JButton();
        jButton11_viewlec = new javax.swing.JButton();
        ld1 = new javax.swing.JTextField();
        ld8 = new javax.swing.JComboBox<>();
        ld = new javax.swing.JTextField();

        view_lecturers.setBackground(new java.awt.Color(102, 51, 109));

        jLabel60_60.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel60_60.setText("Department");

        jLabel62_62.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel62_62.setText("Building");

        jLabel59_59.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel59_59.setText("Faculty");

        jLabel64_64.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel64_64.setText("Rank");

        jLabel58_58.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel58_58.setText("Name");

        jLabel61_61.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel61_61.setText("Center");

        jLabel63_63.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel63_63.setText("Level");

        jLabel57_57.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel57_57.setText("Employee ID");

        jPanel18_18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18_18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel47_47.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel47_47.setText("Lecturer Details");

        javax.swing.GroupLayout jPanel18_18Layout = new javax.swing.GroupLayout(jPanel18_18);
        jPanel18_18.setLayout(jPanel18_18Layout);
        jPanel18_18Layout.setHorizontalGroup(
            jPanel18_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18_18Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel47_47)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel18_18Layout.setVerticalGroup(
            jPanel18_18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18_18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47_47)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton9__viewlec.setBackground(new java.awt.Color(204, 204, 204));
        jButton9__viewlec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9__viewlec.setText(" Back ");
        jButton9__viewlec.setBorder(null);
        jButton9__viewlec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9__viewlecActionPerformed(evt);
            }
        });

        jTextField8_8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField8_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8_8ActionPerformed(evt);
            }
        });

        jTextField9_9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField9_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9_9ActionPerformed(evt);
            }
        });

        jComboBox11_11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox12_12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox13_13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox14_14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jComboBox15_15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextField10_10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField10_10.setForeground(new java.awt.Color(204, 204, 204));
        jTextField10_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10_10ActionPerformed(evt);
            }
        });

        edit_lec1.setBackground(new java.awt.Color(255, 255, 255));
        edit_lec1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_lec1.setText(" Edit ");
        edit_lec1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        edit_lec1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_lec1ActionPerformed(evt);
            }
        });

        delete_lec1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_lec1.setText(" Delete ");
        delete_lec1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton10.setText(" Generate ");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setEnabled(false);

        edit_lecs.setBackground(new java.awt.Color(255, 255, 255));
        edit_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        edit_lecs.setText(" Edit ");
        edit_lecs.setBorder(null);
        edit_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_lecsActionPerformed(evt);
            }
        });

        delete_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete_lecs.setText(" Delete ");
        delete_lecs.setBorder(null);
        delete_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_lecsActionPerformed(evt);
            }
        });

        jPanel34_viewlec.setBackground(new java.awt.Color(135, 19, 135));
        jPanel34_viewlec.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View Lecturer Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel65_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel65_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65_viewlec.setText("Employee ID");

        jLabel68_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel68_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel68_viewlec.setText("Name");

        jLabel69_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel69_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel69_viewlec.setText("Faculty");

        ld2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld2.setForeground(new java.awt.Color(102, 102, 102));
        ld2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "Faculty of Computing", "Faculty of Engineering", "Faculty of Business", "Faculty of Home Science" }));

        jLabel70_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel70_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel70_viewlec.setText("Department");

        ld3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld3.setForeground(new java.awt.Color(102, 102, 102));
        ld3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "Software Engineering", "Infortmation Technology", "Computer Networks", "Interactive Media", "Civil Engineering", "Mechanical Engineering", "Electronic and Telecommuincation Engineering", "Humanities and Science", "Cyber Securrity", "Information System Engineering", "Mechatronic Engineering" }));

        jLabel71_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel71_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71_viewlec.setText("Center");

        ld4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld4.setForeground(new java.awt.Color(102, 102, 102));
        ld4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Center", "Malabe", "Matara", "Kandy", "Jaffna", "Metro", "Kurunegala" }));

        jLabel72_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel72_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel72_viewlec.setText("Building");

        ld5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld5.setForeground(new java.awt.Color(102, 102, 102));
        ld5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Building", "Main Building", "New Building", "Engeering", "Business", "D-Block" }));

        jLabel73_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel73_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73_viewlec.setText("Level");

        ld6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld6.setForeground(new java.awt.Color(102, 102, 102));
        ld6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Level", "1", "2", "3", "4", "5" }));

        jLabel74_viewlec.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel74_viewlec.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74_viewlec.setText("Rank");

        ld7.setEditable(false);
        ld7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld7.setForeground(new java.awt.Color(102, 102, 102));
        ld7.setEnabled(false);
        ld7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ld7ActionPerformed(evt);
            }
        });

        view_lecs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        view_lecs.setText(" View ");
        view_lecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_lecsActionPerformed(evt);
            }
        });

        jButton11_viewlec.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton11_viewlec.setText(" Generate ");
        jButton11_viewlec.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11_viewlec.setEnabled(false);

        ld1.setEditable(false);
        ld1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld1.setForeground(new java.awt.Color(102, 102, 102));
        ld1.setEnabled(false);
        ld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ld1ActionPerformed(evt);
            }
        });
        ld1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ld1KeyPressed(evt);
            }
        });

        ld8.setEditable(true);
        ld8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ld8.setForeground(new java.awt.Color(102, 102, 102));
        ld8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Employee Id" }));

        javax.swing.GroupLayout jPanel34_viewlecLayout = new javax.swing.GroupLayout(jPanel34_viewlec);
        jPanel34_viewlec.setLayout(jPanel34_viewlecLayout);
        jPanel34_viewlecLayout.setHorizontalGroup(
            jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel70_viewlec)
                            .addComponent(jLabel65_viewlec)
                            .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel71_viewlec)
                                    .addComponent(jLabel73_viewlec)
                                    .addComponent(jLabel72_viewlec)))
                            .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel68_viewlec)
                                    .addComponent(jLabel69_viewlec)))))
                    .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel74_viewlec)))
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34_viewlecLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ld1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ld3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ld4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ld5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ld6, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ld8, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ld2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ld7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11_viewlec)
                    .addComponent(view_lecs))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel34_viewlecLayout.setVerticalGroup(
            jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34_viewlecLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_lecs)
                    .addComponent(jLabel65_viewlec)
                    .addComponent(ld8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68_viewlec)
                    .addComponent(ld1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel69_viewlec))
                .addGap(58, 58, 58)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel70_viewlec)
                    .addComponent(ld3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ld4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71_viewlec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72_viewlec))
                .addGap(61, 61, 61)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel73_viewlec))
                .addGap(56, 56, 56)
                .addGroup(jPanel34_viewlecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11_viewlec)
                    .addComponent(jLabel74_viewlec))
                .addGap(63, 63, 63))
        );

        ld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout view_lecturersLayout = new javax.swing.GroupLayout(view_lecturers);
        view_lecturers.setLayout(view_lecturersLayout);
        view_lecturersLayout.setHorizontalGroup(
            view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(572, 572, 572)
                        .addComponent(jButton9__viewlec, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(edit_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(delete_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(828, 828, 828)
                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3103, Short.MAX_VALUE)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel59_59)
                                            .addComponent(jLabel58_58))
                                        .addGap(116, 116, 116))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel61_61)
                                        .addGap(115, 115, 115))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel60_60)
                                        .addGap(93, 93, 93))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                        .addComponent(jLabel57_57)
                                        .addGap(76, 76, 76)))
                                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox13_13, javax.swing.GroupLayout.Alignment.TRAILING, 0, 184, Short.MAX_VALUE)
                                    .addComponent(jComboBox12_12, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox11_11, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField9_9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField8_8, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel62_62)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox14_14, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel63_63)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox15_15, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                                    .addComponent(jLabel64_64)
                                    .addGap(117, 117, 117)
                                    .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(view_lecturersLayout.createSequentialGroup()
                                            .addComponent(edit_lec1)
                                            .addGap(53, 53, 53)
                                            .addComponent(delete_lec1))
                                        .addComponent(jTextField10_10, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(55, 55, 55)
                .addComponent(jButton10)
                .addGap(101, 101, 101))
            .addGroup(view_lecturersLayout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jPanel34_viewlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view_lecturersLayout.setVerticalGroup(
            view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_lecturersLayout.createSequentialGroup()
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(853, 853, 853)
                        .addComponent(jPanel18_18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_lecturersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel34_viewlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9__viewlec, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edit_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_lecs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)))
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57_57))
                .addGap(18, 18, 18)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58_58))
                .addGap(38, 38, 38)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox11_11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59_59))
                .addGap(27, 27, 27)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox12_12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60_60))
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox13_13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61_61)))
                    .addGroup(view_lecturersLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox14_14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel62_62))
                .addGap(33, 33, 33)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox15_15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel63_63))
                .addGap(44, 44, 44)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10_10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10)
                    .addComponent(jLabel64_64))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(view_lecturersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_lec1)
                    .addComponent(delete_lec1))
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4731, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(view_lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(view_lecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9__viewlecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9__viewlecActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturersPanel());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_jButton9__viewlecActionPerformed

    private void jTextField8_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8_8ActionPerformed

    private void jTextField9_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9_9ActionPerformed

    private void jTextField10_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10_10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10_10ActionPerformed

    private void edit_lec1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_lec1ActionPerformed
        // TODO add your handling code here:

        generator.Parent.removeAll();
        generator.Parent.add(new lecturer_edit());
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_edit_lec1ActionPerformed

    private void edit_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_lecsActionPerformed
        // TODO add your handling code here:
        
        String empID = ld8.getSelectedItem().toString();
        String lecName = ld1.getText();
        String lecFaculty = ld2.getSelectedItem().toString();
        String lecDepartment = ld3.getSelectedItem().toString();
        String lecCenter = ld4.getSelectedItem().toString();
        String lecBulding = ld5.getSelectedItem().toString();
        String lecLevel = ld6.getSelectedItem().toString();
        String lecRank = ld7.getText();

        System.out.println(lecBulding);
        System.out.println(lecCenter);
        System.out.println(lecRank);
        
        generator.Parent.removeAll();
        generator.Parent.add(new lecturer_edit(empID, lecName, lecFaculty, lecDepartment, lecCenter, lecBulding, lecLevel, lecRank));
        generator.Parent.repaint();
        generator.Parent.revalidate();
    }//GEN-LAST:event_edit_lecsActionPerformed

    private void delete_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_lecsActionPerformed
        // TODO add your handling code here:

        try {

            //delete lecturer details from database
            int empId = Integer.parseInt(ld8.getSelectedItem().toString());

            Statement s = con.createStatement();
            s.execute("delete from lec where empID=" + empId);
            JOptionPane.showMessageDialog(this, "Record Are Deleted!");

           
            s.close();
            

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Can't Delete Records!");
        }
    }//GEN-LAST:event_delete_lecsActionPerformed

    private void ld7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ld7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld7ActionPerformed

    private void view_lecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_lecsActionPerformed
        // TODO add your handling code here:

        Functionlec f = new Functionlec();

        ResultSet rs = null;

        String lecName = "name";
        String lecFaculty = "faculty";
        String lecDepartment = "dept";
        String lecCenter = "center";
        String lecBulding = "building";
        String lecLevel = "level";
        String lecRank = "rank";

        rs = f.find(ld8.getSelectedItem().toString());

        try {

            //view the lecturer details
            if (rs.next()) {

                ld1.setText(rs.getString("name"));
                ld2.setSelectedItem(rs.getString("faculty"));
                ld3.setSelectedItem(rs.getString("dept"));
                ld4.setSelectedItem(rs.getString("center"));
                ld5.setSelectedItem(rs.getString("building"));
                ld6.setSelectedItem(rs.getString("level"));
                ld7.setText(rs.getString("rank"));
            } else {
                JOptionPane.showMessageDialog(null, "Sorry, No Data Found!");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_view_lecsActionPerformed

    private void ld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld1ActionPerformed

    private void ld1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ld1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ld1KeyPressed

    private void ldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete_lec1;
    private javax.swing.JButton delete_lecs;
    private javax.swing.JButton edit_lec1;
    private javax.swing.JButton edit_lecs;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11_viewlec;
    private javax.swing.JButton jButton9__viewlec;
    private javax.swing.JComboBox<String> jComboBox11_11;
    private javax.swing.JComboBox<String> jComboBox12_12;
    private javax.swing.JComboBox<String> jComboBox13_13;
    private javax.swing.JComboBox<String> jComboBox14_14;
    private javax.swing.JComboBox<String> jComboBox15_15;
    private javax.swing.JLabel jLabel47_47;
    private javax.swing.JLabel jLabel57_57;
    private javax.swing.JLabel jLabel58_58;
    private javax.swing.JLabel jLabel59_59;
    private javax.swing.JLabel jLabel60_60;
    private javax.swing.JLabel jLabel61_61;
    private javax.swing.JLabel jLabel62_62;
    private javax.swing.JLabel jLabel63_63;
    private javax.swing.JLabel jLabel64_64;
    private javax.swing.JLabel jLabel65_viewlec;
    private javax.swing.JLabel jLabel68_viewlec;
    private javax.swing.JLabel jLabel69_viewlec;
    private javax.swing.JLabel jLabel70_viewlec;
    private javax.swing.JLabel jLabel71_viewlec;
    private javax.swing.JLabel jLabel72_viewlec;
    private javax.swing.JLabel jLabel73_viewlec;
    private javax.swing.JLabel jLabel74_viewlec;
    private javax.swing.JPanel jPanel18_18;
    private javax.swing.JPanel jPanel34_viewlec;
    private javax.swing.JTextField jTextField10_10;
    private javax.swing.JTextField jTextField8_8;
    private javax.swing.JTextField jTextField9_9;
    private javax.swing.JTextField ld;
    private javax.swing.JTextField ld1;
    private javax.swing.JComboBox<String> ld2;
    private javax.swing.JComboBox<String> ld3;
    private javax.swing.JComboBox<String> ld4;
    private javax.swing.JComboBox<String> ld5;
    private javax.swing.JComboBox<String> ld6;
    private javax.swing.JTextField ld7;
    private javax.swing.JComboBox<String> ld8;
    private javax.swing.JButton view_lecs;
    private javax.swing.JPanel view_lecturers;
    // End of variables declaration//GEN-END:variables

    private void lecturerSearch(){      
        String sql = "select * from lec";       
        try{            
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                ld8.addItem(rs.getString("empID"));                
            }                  }
        catch(Exception e){           
             JOptionPane.showMessageDialog(this, JOptionPane.ERROR_MESSAGE);            
        }   }
    
    
    
    public class Functionlec {

        Connection con = null;
        ResultSet rs = null;
        PreparedStatement ps = null;

        public ResultSet find(String s) {

            try {

                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/timetable", "root", "");
                ps = con.prepareStatement("select * from lec where empID=?");
                ps.setString(1, s);
                rs = ps.executeQuery();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

            return rs;

        }

    }
}
